### ISSUE TITLE
A way to delete a field from document via deepstream Record

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io-client-js#111]
See https://github.com/deepstreamIO/deepstream.io/issues/119

**Comment by ronag** [comment]
Wouldn't merge strategies resolve this?

**Comment by yasserf** [comment]
This is more around being able to delete values within a record object

record.get() -> { name: 'bob', age: 26 }
record.set( 'name', undefined )
record.get() -> { age: 26 }

Given the way we json.stringify and parse the object this actually works, but we want to add tests for different scenarios and arrays
