### ISSUE TITLE
Local Only Records?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#116]
It would be nice if I could create Records that are local to the application, i.e. it is global for the application but not synced over to the server.

This way I could create an application based solely on deep stream API's instead of having to involve a local state framework such as Redux.

**Comment by yasserf** [comment]
I like the concept, but this will be a huge piece of work since we would need to put guards across any timeouts / connection interactions ( which are alot ).

Be worth thinking about this after offline first feature is implemented since it requires a few features from there.

**Comment by yasserf** [comment]
Closing this since it isn't on our near/medium term roadmap.
