### ISSUE TITLE
allow discard to take a 'true' argument that does a force discard and disposes subscription to server

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io-client-js#119]
This will be a convenience method for development purposes or as a stopgap for memory leaks

**Comment by ronag** [comment]
Could this not be solved by putting every record reference in a `WeakSet` and having a `setInterval` comparing it with a list of active records? For debugging purposes... i.e. this way you could easily detect and warn for "leaked" records.
