### ISSUE TITLE
Client Side LRU Record Cache

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#121]
Some applications will rapidly create and destroy the same records. Would be nice to have a configurable LRU Record Cache on the client side.

**Comment by WolframHempel** [comment]
Hm, could you provide a usecase for the record creation / destruction?

**Comment by ronag** [comment]
In our application the client often performs searches which can result in 100-200 records being fetched. However, often the records are the same. Now, we could of course perform the caching in our application layer but I think this could be a good optimisation in general, i.e. the possibility to have stale records in memory at the client.

**Comment by yasserf** [comment]
This is implemented in V4

https://deepstream.io/releases/client-js/v4-0-0/index.html (offline storage, anchor links not implemented yet 🙈
