### ISSUE TITLE
Does opening the same record multiple times re-use existing handles?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#124]
Does opening the same record multiple times re-use existing handles?

i.e. is this ALWAYS true?

`ds.record.get(id) === ds.record.get(id)`

**Comment by WolframHempel** [comment]
it's almost always true. `myRecord = ds.record.getRecord(id)` will return the same instance of the record, but increment its usage count by one. `myRecord.discard()` will decrement its usage count by one. Once the usage count reaches zero, the server is notified that it no longer needs to send updates for this record to the client and the record instance is destroyed. This means

```javascript
//this is true
var recA = ds.record.getRecord( 'someRecord' );
var recB = ds.record.getRecord( 'someRecord' );
recA === recB // true

//but this is false
var recA = ds.record.getRecord( 'someRecord' );
recA.discard();
var recB = ds.record.getRecord( 'someRecord' );
recA === recB // false
```

**Comment by ronag** [comment]
Perfect. Thank you!
