### ISSUE TITLE
UNSOLICITED_MESSAGE if discarded right after set

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#126]
```
    const sceneRecord = ds.record.getRecord(`scene/${id}`)

    sceneRecord.set({
      tag: 'file:1',
      input: id
    })

    sceneRecord.discard()
```

Will cause a `UNSOLICITED_MESSAGE` message error unless `discard` is removed... which is strange...

**Comment by WolframHempel** [comment]
`ds.record.getRecord(`scene/${id}`)` triggers a read operation, discard is called synchronously directly after. So by the time the asynchronous read result arrives the record is already discarded, prompting an UNSOLICITED_MESSAGE warning. You can do two things:

- Ignore it. This is perfectly fine - UNSOLICITED_MESSAGE is just a warning to draw your attention towards potential problems - which don't exist in this case

- use `whenReady`

```javascript
const sceneRecord = ds.record.getRecord(`scene/${id}`)

sceneRecord.whenReady(() => {
	sceneRecord.set({
      tag: 'file:1',
      input: id
    });

    sceneRecord.discard();
});
    
```

**Comment by yasserf** [comment]
Worth noting this has been fixed in the next release, discard only occurs once the record has actually been retrieved now ( by internally using when ready ).
