### ISSUE TITLE
Merge Strategy and record references?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#135]
How are merge strategies applied to a record in the case where I have several references to it?

e.g.

```
// Some part of the application
const rec1 = ds.record.getRecord(id)
rec.setMergeStrategy(merge1)

// Another part of the application
const rec2 = ds.record.getRecord(id)
rec.setMergeStrategy(merge2)

// What happens now??? Is merge1 or merge2 used?
```

This is why I would argue that merge strategies should be applied on a per mutation basis, not on a per record basis. Though I understand that has its own implications e.g. when a conflict originates from the server and not the client.

**Comment by ronag** [comment]
So the answer is that `merge2` would be used. This can potentially cause a lot of confusion...

**Comment by yasserf** [comment]
Your returning the same instance of the record and overriding it's merge functionality. I would argue if you merge data on the same record in separate ways thats more confusing.

**Comment by ronag** [comment]
> merge data on the same record in separate ways thats more confusing.

Indeed. But right now I could have 2 developers in the same application setting different merge strategies  on a record and then being totally confused why strange things are happening. I can agree that the way conflict handling works in deep stream you should only have one merge strategy. However, the API should enforce that or at least be somewhat self-documenting about it.
