### ISSUE TITLE
How does Deepstream handle multiple data-providers that match a pattern?

### ISSUE THREAD

**Issue by kolpax** [deepstreamIO/deepstream.io-client-js#137]
What happens when multiple servers have the same data-providers for HA or somehow the pattern for multiple data-providers matches the name? Will one win or will both execute?

**Comment by yasserf** [comment]
Sorry, what do you mean by 'for HA'?

Currently all providers would be notified once a pattern is matched.

**Comment by kolpax** [comment]
@yasserf Sorry, for high availability.

**Comment by kolpax** [comment]
@yasserf Shouldn't that work through RCP though?

**Comment by yasserf** [comment]
Closing as duplicate of #211
