### ISSUE TITLE
subscribe is never called with the initial value on created but not set records?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#138]
e.g.
```
const rec = ds.record.getRecord(id)
rec.subscribe(function (value) {
  console.log(value)
}, true)
```

Given that records are create on `getRecord` I would expect the above code to print `{}`...

Or is the record state after `getRecord` something in between exists and doesn't exists?

**Comment by yasserf** [comment]
getRecord is async if the record isn't already loaded client side, which means you won't have the data from the server immediately afterwards when you do a subscribe( fn, true )

**Comment by ronag** [comment]
@yasserf: Yes, but shouldn't it eventually print `{}`?

**Comment by yasserf** [comment]
This is got to do with it just being async

```
const rec = ds.record.getRecord(id) <- async call to get data
rec.subscribe(function (value) {
  console.log(value)
}, true) <- immediate callback that gets triggered before record is created
```

```
const rec = ds.record.getRecord(id) <- async call to get data
ds.record.snapshot( function() { 
} ) <- also async, hences gets called with data
```

**Comment by yasserf** [comment]
The subscribe method should print {} once the initial data comes back though. Is that not the case?

**Comment by ronag** [comment]
>  Is that not the case?

No it's not...

**Comment by ronag** [comment]
```
const rec = ds.record.getRecord(id) <- async call to get data
ds.record.snapshot( function() { 
} ) <- also async, hences gets called with data
```

It's not async, see: https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/src/record/record-handler.js#L138

It should be, at the least:

```
RecordHandler.prototype.snapshot = function( name, callback ) {
	if( this._records[ name ] ) {
		setImmediate(callback.bind(null, null, this._records[ name ].get() );
	} else {
		this._snapshotRegistry.request( name, callback );
	}
};
```

**Comment by ronag** [comment]
The reason this is an issue for us is that we now have to use a rather silly implementation:

```
observe (recordName, path) {
    const record = ds.record.getRecord(recordName)
    return Observable
      .create(o => {
        record.whenReady(() => {
          o.next(record.get(path))
          o.complete()
        })
      })
      .concat(Observable
        .create(o => {
          const update = (value) => o.next(value)
          record.subscribe(path, update)
          return () => {
            record.unsubscribe(path, update)
            record.discard()
          }
        })
      )
  }
```

**Comment by yasserf** [comment]
Yup your totally right, snapshot should only be sync if ready. If you raise a bug well'll make sure to fix it for the next release.

**Comment by ronag** [comment]
Of course I'm right. I've been reading this book, http://www.amazon.com/How-Not-Be-Wrong-Mathematical/dp/0143127535/ref=sr_1_1?ie=UTF8&qid=1464712889&sr=8-1&keywords=How+Not+to+Be+Wrong.

I'll make a separate issue.

**Comment by ronag** [comment]
@yasserf: The problem is here: https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/src/record/record.js#L514

If the record is created then the oldValue will be `{}` thus `subscribe` will not receive it...

**Comment by ronag** [comment]
I think this is a more correct implementation:

```javascript
Record.prototype.subscribe = function( path, callback, triggerNow ) {
	var i, args = this._normalizeArguments( arguments );

	if( this._checkDestroyed( 'subscribe' ) ) {
		return;
	}

	if( args.triggerNow ) {
		this.whenReady(function () {
			if( args.triggerNow) {
				if( args.path ) {
					args.callback( this._getPath( args.path ).getValue() );
				} else {
					args.callback( this._$data );
				}
			}
			this._eventEmitter.on( args.path || ALL_EVENT, args.callback );
		})
	} else {
		this._eventEmitter.on( args.path || ALL_EVENT, args.callback );
	}
};
```
