### ISSUE TITLE
Callbacks should always be called asynchronously or maybe not?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#141]
http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony

I've noticed that a lot of callbacks are sometimes invoked synchronously. However, that can cause a lot of weird bugs if the caller is not ready for it. Though, I understand, possibly given e.g. react and input fields why you would want it to be synchronous.

I think that either it should be very explicitly documented that callbacks can be called synchronously or it should be an opt in behaviour.

**Comment by WolframHempel** [comment]
I'm aware that this has been brought up before and many users feel that way. Our background is in building high performant trading apps that require granular control off the rendering loop and favor speed and predictability over developer convenience. To enable these use-cases it helps for data to be available as quickly as possible (e.g. synchronously) if the data is already loaded.

**Comment by ronag** [comment]
@WolframHempel: Ok. I would at least appreciate if the callback behaviour was documented.
