### ISSUE TITLE
Merge Strategy should not be applied on a record reference

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#144]
Considering https://github.com/deepstreamIO/deepstream.io-client-js/issues/135 I think it is a very bad idea to apply merge strategies on a record reference since it can make things very confusing. The way the API is now you would easily be lead to believe that you can apply merge strategies on a record reference basis, which is not the case.

I'm not sure what a better API would be but somehow we have to make sure that a record has a global merge strategy.

**Comment by ronag** [comment]
Maybe merge strategies should be registered on a pattern? They could still collide the same way as data providers can be then the risk is at least manageable.

e.g.
```javascript
ds.record.setMergeStrategy('video/*', mergeFunction)

const rec = ds.record.getRecord('video/1')
```

**Comment by yasserf** [comment]
This actually is a nice to have, but we won't be implementing it ourselves since we have higher priority issues to concentrate on.

**Comment by ronag** [comment]
One alternative would be to actually support multiple merge strategies on the same record, e.g. something like:

```javascript
async function merge(localValue, remoteValue, remoteVersion) {
  for (let inner of new Set(this._mergeStrategies)) {
    localValue = await inner(localValue, remoteValue, remoteVersion)
  }
}
```

**Comment by yasserf** [comment]
I think the first part ( merge conflicts based on patterns ) might be a nice addition ontop of a global. But didn't get my head around the second part tbh

**Comment by yasserf** [comment]
A quick win for this would be to throw an exception if you set a merge strategy more than once for sanity checks as in  #135. Would you find that to be an acceptable solution?

**Comment by yasserf** [comment]
So the following API's we have are:

```
// Set merge strategy globally when initialising the client
client = deepstream('localhost', { mergeStrategy: deepstream.MERGE_STRATEGIES.LOCAL_WINS })

// Set merge strategy on a pattern when initialising the client
client = deepstream('localhost', { mergeStrategy: deepstream.MERGE_STRATEGIES.LOCAL_WINS })
client.record.setMergeStrategyRegExp('name', (localValue, localVersion, remoteValue, remoteVersion, callback) => {
    callback(error, mergedData)
})

// Set merge strategy on a per record basis
rec = ds.record.getRecord('some-record')
rec.setMergeStrategy(deepstream.MERGE_STRATEGIES.REMOTE_WINS)
```

We actually have a merge service, since setData doesn't have an actual record

```
  public setMergeStrategy (recordName: string, mergeStrategy: MergeStrategy): void {
    if (typeof mergeStrategy === 'function') {
      this.recordServices.mergeStrategy.setMergeStrategyByName(recordName, mergeStrategy)
    } else {
      throw new Error('Invalid merge strategy: Must be a Function')
    }
  }

  public setMergeStrategyRegExp (regexp: RegExp, mergeStrategy: MergeStrategy): void {
    if (typeof mergeStrategy === 'function') {
      this.recordServices.mergeStrategy.setMergeStrategyByPattern(regexp, mergeStrategy)
    } else {
      throw new Error('Invalid merge strategy: Must be a Function')
    }
  }
```

The main issue still exists where merge strategies are not on individual records of the same name, but thats a pretty far out issue 😅
