### ISSUE TITLE
Package beta to npm

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#154]
If you would package and publish beta releases to npm we would be willing to use the beta versions in our ongoing development phase.

I believe we could help finding lots of bugs. We've already found several bugs in the current stable releases buts it's a bit unclear whether they are fixed or will be fixed in the 1.0 release.

**Comment by WolframHempel** [comment]
Thanks. No need to publish beta releases to NPM though, this would also work:

```json
{
	"dependencies": {
		"deepstream.io":"https://github.com/deepstreamIO/deepstream.io.git#v1.0.0-beta.4"
	}
}

```

**Comment by ronag** [comment]
@WolframHempel: The client doesn't have a beta tag.

**Comment by yasserf** [comment]
Added

**Comment by yasserf** [comment]
Can you confirm if it works and close accordingly? thanks
