### ISSUE TITLE
When does provider unsubscribe disconnected clients?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#155]
I'm testing the provider functionality and I've noticed that the 'isSubscribe: false` never happens when a client is disconnected?

```javascript
ds.record.listen('search', (key, isSubscribed) => {
  logger.debug({ key, isSubscribed })
})
```

Never prints `isSubscribed` as false...?

**Comment by ronag** [comment]
Bump. This a quite a serious issue for us and I would appreciate some feedback? @yasserf

**Comment by WolframHempel** [comment]
Is the process that listen's also providing the given record? If so it counts as a subscriber and keeps the subscriber count above 0

**Comment by ronag** [comment]
@WolframHempel: Yes, it is... that might explain it. But not doing it like that has some performance implications...

**Comment by ronag** [comment]
Actually, this a a big issue for me.

**Comment by ronag** [comment]
Is there any way to create a "weak" reference to a record?

**Comment by ronag** [comment]
The problem here is that, yes I could unsubscribe, but then every time I want to update the record I have to read it back...

**Comment by yasserf** [comment]
Hey Ronag,

This ties into our listening epic ( TBC ). We will be spending a sprint on making sure we can get listening to work in a way that makes sense and clusters well.

I'm afraid till then you'll have to discard the record ( could do so on a timeout to avoid the performance overhead, which does tie in to your other issue )
