### ISSUE TITLE
yielded packet processing

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#159]
Right now the UI can become unresponsive or laggy if there is a lot of deepstream traffic going on. Would  be nice if packet processing could yield using e.g. `requestIdleCallback`.

**Comment by yasserf** [comment]
Interesting, we wrote the merchant with alot  of traffic and never got close to the app becoming laggy. Can you provide an example that I can see that shows deepstream  slowing down an application?

**Comment by ronag** [comment]
I can't provide an example. But I have a infinite scroll list that dynamically loads in items and I want to keep my app running at 60 fps. However, the deepstream packet processing sometimes take more than 15ms to complete in a single frame.

**Comment by ronag** [comment]
Either way, I can see no harm in yielding the packet processing...

**Comment by ronag** [comment]
@yasserf: Another thing worth to look at is to put the deepstream processing in a worker.

**Comment by ronag** [comment]
Closed in favour of #200
