### ISSUE TITLE
Documentation - login callback

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#168]
The docs for login callback in the code docs seem to be wrong.

```* @param   {Function} callback   Will be called with either (true) or (false, errorType, errorMessage)```

However, looking at the code, that is not the case. Honestly, looking at the code I'm totally confused as to what is actually passed t the callback.

Some clarification?

**Comment by yasserf** [comment]
This should now be

```javascript
login( {}, (success, data) => {
  // success true or false
 // data is whatever is returned by the authentication handler, and is not longer controlled by us.
} )
```

In the case of our authentication handler, data would be an error message if username or password is missing.

```javascript
	isValidUser( connectionData, authData, callback ) {
		if( typeof authData.username !== STRING ) {
			callback( false, { clientData: 'missing authentication parameter username' } );
			return;
		}
...
```

and in the case of the http server it would whatever the http server returns false with

```javascript
if( this._settings.permittedStatusCodes.indexOf( response.statusCode ) === -1 ) {
			this._callback( false, response.body || null )
		}
```
