### ISSUE TITLE
listen example is incorrect

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#170]
The following example doesn't work as expected since `isSubscribed` would never be false since the listener itself has the last reference...

```javascript
var raceHorseRecords = {};

client.record.listen( 'raceHorse/.*', function( match, isSubscribed ) {
    /*
         + match = 'raceHorse/fast-betty'
         + isSubscribed = true
     */
    var horseName = match.split( '/' )[ 1 ],
        updateRecord = function( data ){
            raceHorseRecords[ match ].set( data );
        };

    if( isSubscribed ) {
        raceHorseRecords[ match ] = client.record.getRecord( match );

        // assuming we have a raceHorseDataProvider class
        raceHorseDataProvider.subscribe( horseName, updateRecord );
    } else {
        raceHorseRecords[ match ].discard();
        delete raceHorseRecords[ match ];
        raceHorseDataProvider.unsubscribe( horseName, updateRecord );
    }
});

// This function will now be called whenever a client requests a record
// with a matching name, e.g.
client.record.getRecord( 'raceHorse/fast-betty' );
```

**Comment by ronag** [comment]
See, https://github.com/deepstreamIO/deepstream.io-client-js/issues/155

**Comment by ronag** [comment]
@yasserf: Any feedback on this?

**Comment by ronag** [comment]
I think `isSubscribed` should be replaced with `numSubscribers`. That way one can get around the issue.

**Comment by ronag** [comment]
@yasserf: Please remind me how this is resolved with the new listen functionality?

**Comment by yasserf** [comment]
The publisher will be told the subscription was discarded even if the publisher is also the subscriber but the last one in the cluster. This means a publisher should not normally depend on subscribing to something listening in the same client outside of the listen callback. It will work, but  with known side effects.

**Comment by ronag** [comment]
@yasserf: That just made my head spin... so it will work but not really?

**Comment by ronag** [comment]
Ah, so it will receive `isSubscribed=false` even if it is subscribing itself. That sounds totally reasonable. What are these 'known side effects'?

**Comment by yasserf** [comment]
The provider is considered a subscriber if it subscribes to the record outside of the listen function,    but if someone else subscribes and unsubscribes that provider will get a subscription stopped, even though it is still subscribed outside of the listen. That's mainly  done to reduce operations on hot paths.
