### ISSUE TITLE
Feature Request - Don't Perform Deep Copies

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#172]
Right now deepstream will perform deep copies of all records when requesting data. We would prefer if it just called `Object.freeze` or some similar solution.

**Comment by yasserf** [comment]
Few arguments why we shouldn't apply this:
1) Object.freeze is just a shallow solution, doesn't go deeper so recursion still needed
2) Object.freeze does not return a variable, meaning we would need to freeze the object every time we get it and then recreate it when the user sets something
3) Object.freeze is not suppported in the same range of browsers deepstream client currently supports

Be interesting to see the performance improvements though, they would have to be a good margin for it to be worth the change.

**Comment by ronag** [comment]
https://github.com/rtfeldman/seamless-immutable

**Comment by yasserf** [comment]
Our API allows the following:

```
x = record.get();
x.bob = 'something';
record.set( x );
```
object.freeze doesn't support that. We have an issue open somewhere for automated deltas, meaning that setting an entire object could try to computer the change and only sends down the patch.

Can I ask what using freeze would fix/improve? I understand the arguments for and against using immutable objects, but would need a valid error/issue with the current API to consider moving away from doing deep copies.

Thanks!

**Comment by ronag** [comment]
@yasserf: It's a bit of a performance issue but we can work around it by splitting into smaller records.

We perform frame by frame updates on a lot of records client side and doing deep copies every time is slow.

It's a minor issue.
