### ISSUE TITLE
Emit event when max reconnect attempts has been reached

### ISSUE THREAD

**Issue by kolpax** [deepstreamIO/deepstream.io-client-js#175]
Currently I have to count the reconnect attempts manually. Would be nice to have an event for when no more reconnect attempts will be made.

I use it to separate warnings from errors in my project. A reconnect is a warning while the last reconnect failed is an error.

**Comment by yasserf** [comment]
We will emit a 

`
C.EVENT.exports.MAX_RECONNECTION_ATTEMPTS_REACHED
`
