### ISSUE TITLE
unprovide

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#177]
In order to implement graceful shutdown in user land we need at least a `rpc.unprovide` which will stop listening for new requests but lets existing requests finish.

**Comment by ronag** [comment]
This could actually be achieve by simply rejecting all messages.

**Comment by yasserf** [comment]
Will look into the specs for this later to see how it currently works in depth.

**Comment by yasserf** [comment]
Good news is this works on the server side and only requires a client API

**Comment by yasserf** [comment]
@ronag Actually, how is this not the case? Unprovide says it unsubscribes as a provider, but shouldn't affect current RPCs

**Comment by yasserf** [comment]
Answer is missing in documentation!!
