### ISSUE TITLE
Problem with subscribe after connection close

### ISSUE THREAD

**Issue by ealves-pt** [deepstreamIO/deepstream.io-client-js#184]
I have problems with subscription after closing the connection. My use case is the following:

```javascript
listChanged (list) {
  list.forEach((taId) => {
    if (!this.taRecords[taId]) {
      const taRecord = this.client.record.getRecord(`ta/${taId}`)
      taRecord.subscribe(this.taChanged, true)
      this.taRecords[taId] = taRecord
    }
  })
},
taChanged (ta) {
  this.addTa(ta)
},
subscribeTas () {
  this.taRecords = {}
  this.taList = this.client.record.getList(`i/${this.cId}/ta`)
  this.taList.subscribe(this.listChanged, true)
},
unsubscribeTas () {
  if (this.taList) {
    for (let id in this.taRecords) {
      if (this.taRecords.hasOwnProperty(id)) {
        this.taRecords[id].unsubscribe(this.taChanged)
      }
    }
    this.taList.unsubscribe(this.listChanged)

    this.taRecords = {}
    this.taList = null
  }
}
```

So I call `client.login()` for user authentication and once the connection state is OPEN I call the method `subscribeTas`.

Then when the user wishes to logout I call `unsubscribeTas` and then `client.close()`. The connection state is now CLOSED.

Now if I authenticate again, the connection state is OPEN, but the subscriptions are not triggered by any changes and they actually only display the cached values that existed before the connection was closed.

Any idea of what might be wrong with this picture?

**Comment by yasserf** [comment]
Can you confirm that this is what your doing:

1) Login
2) Get List
3) Subscribe to List
4) Unsubscribe to List
5) Logout
6) Login again
7) Get list again? -< Do you do this, my guess is your using the older list still
7) Resubscribe to list


Subscribe/Unsubscribe methods in records are all local, mainly since they are mainy permutations your updates can be received in and so isn't a one to one mapping. In order to inform the server you would need to do a [discard](https://deepstream.io/docs/client-js/datasync-list/#discard) instead, which sends an unsubscribe message to the server.

**Comment by ealves-pt** [comment]
@yasserf 

1) ✔️ 
2) ✔️ (I call `subscribeTas()` that get the list)
3) ✔️ (subscription is done inside `subscribeTas()`)
4) ✔️ (before calling `client.close()` I call `unsubscribeTas()` that unsubscribes the list
5) ✔️
6) ✔️ 
7) ✔️ (again `subscribeTas()` is called)
8) ✔️ (same as step 3.)

Actually when `this.taList.subscribe(this.listChanged, true)` is executed the callback is triggered but receives the old value.

Even if I call `discard()` instead of `unsubscribe()` the issue remains.

Actually, is there any right order on doing that stuff. Should I call `unsubscribe` and  the `discard` or is discard enough?

**Comment by ronag** [comment]
@ealves-pt: As a general rule you should always call `unsubscribe` since currently records are reference counted and subscriptions live on the record instance.

**Comment by ronag** [comment]
@ealves-pt: I think just making sure to `discard` all references before re-connecting would resolve your issue. But I believe that is only a workaround.

**Comment by yasserf** [comment]
Client should re-subscribe to all records that have not been discarded.

To explain a bit further about the internal workings:

When you first get a record, it is created new. 
When you get that record again, it returns a reference to the existing record and bumps up the usage.
Whenever you subscribe to that record from the single record instance will contain all the subscriptions.
When you discard the record, you are just decrementing the usage count, so all subscriptions are still alive.
When you discard all records ( and we'll also be adding a force discard to ignore usage) then what happens is that record will be disposed, and the next time you request it it be created new, regardless if you unsubscribe.

As such, it would be best practice to always unsubscribe before doing a discard.

@ronag All subscriptions are remade on a reconnect. Record subscriptions are only local so all that is sent out to the server on a reconnect is a subscribe and all the listen patterns. Same for events and RPC.

**Comment by ealves-pt** [comment]
@yasserf thanks for the explanation. I will go through the code again and make sure that everything is being done properly and I'll leave an update here either I solve it or not.

**Comment by yasserf** [comment]
If not, if you can provide a full gist I can try it out on our side

**Comment by ealves-pt** [comment]
Ok first issue that I'm encountering.

```javascript
{
  ready () {
    this.list = this.client.subscribe('m/a')
    this.list.subscribe(this.changed, true)
  },
  changed (list) {
    // Do something...
    console.log('changed')
  },
  unsubscribe () {
    this.list.unsubscribe(this.changed)
  },
  discard () {
    this.list.discard()
  }
}
```

Ok, I have a simple web component that subscribes to a list when it's ready and before the component is destroyed it unsubscribes.

So this is what happens:

``` javascript
component.subscribe() // Logs: 'changed'
component.list._record.usages // 1
component.unsubscribe()
component.list._record.usages // 1
component.discard() // Throws "Uncaught Error: MESSAGE_PERMISSION_ERROR: NOT_AUTHORIZED (R)" and "Uncaught Error: ACK_TIMEOUT: m/a (R)"
component.list._record.usages // 0
```

**Comment by yasserf** [comment]
Yeah, it appears you have implemented permissions that doesn't allow you to request a list called 'm/a'.

Can you confirm? Could you also provide your versions of the client and your permission handler ( if valve your permissions would help too )

**Comment by ealves-pt** [comment]
That is weird because the subscription works and I receive updates. I'm not using valve.

Regarding the versions:
```
"deepstream.io-client-js": "^0.5.0",
"deepstream.io": "^0.9.0"
```

I have managed to fix the permission for the `Uncaught Error: MESSAGE_PERMISSION_ERROR: NOT_AUTHORIZED (R)`.

Now the subscription is working after I close the connection and login again.

I still have the `Uncaught Error: ACK_TIMEOUT: m/a (R)` but I will do more research to track what might be wrong.

Anyway, the issue I've reported is a non-issue so I will close this.

@yasserf thanks for your help 👍

**Comment by yasserf** [comment]
Hey,

Might be worth upgrading to 1.0, we done a large amount of improvements. For example, when a message denied is recieved you won't get a read, which meant you'll get an ack timeout. 

Upgrade should be mostly backwards compatible, couple of issues are in change log
