### ISSUE TITLE
Do not force using TCP for Node.js

### ISSUE THREAD

**Issue by timaschew** [deepstreamIO/deepstream.io-client-js#185]
Currently it always defaults to tcp on Node.js which is tied to a specific port. Using engineio (or something different in future) is bound to another port

When using heroku you can only expose one port. This means you can't provide connections for browsers and Node.js at the same time.

**Comment by yasserf** [comment]
This should be an option that uses enums for consistency across different clients.

I wouldn't use engineIO as a name though since their implementations in non-js languages are not well under our control, so be good to use:

```
C.CONNECTION_TYPE.TCP || C.CONNECTION_TYPE.WEBSOCKET
```
