### ISSUE TITLE
Subscribing to all records?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#197]
Is there a way I can subscribe to all records that match a specific pattern? i.e. currently we are indexing re-thinkdb into elastic search. However, I would much prefer avoiding the re-thinkdb dependency and simply index directly from deepstream. However, that requires a way to enumerate all records that match a specific pattern.

**Comment by yasserf** [comment]
Not yet no. That will be possible once we implement Collections, but that will be early next year.
