### ISSUE TITLE
Feature Request - Record Alias

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#198]
We're using the pattern where we put arguments as a "query" string in the record name. Similar to how the rethinkdb provider works.

This works great. However, when using e.g. rethinkdb as the storage connector there is a limit on the record name length. Which is a bit problematic when the query string is large.

The way we solve this currently is exclude all "domain/id?arguments" records from storage, hash the arguments and create a non excluded record, and then sync the hashed and persisted record with the non-hashed and non-persisted records.

This is rather ugly both from complexity and performance perspective.

It would be nice if one could create record name aliases that the server resolves, e.g.

``` javascript

const rec = ds.record.getRecord(`search?${JSON.stringify(query)}`)

// Server

ds.listen('search?*', (subject) => {
  const query = JSON.parse(subject.match(/search(.*)/)[0])
  const id = `search/${hash.MD5(query)}`
  ds.record.alias(subject, id)
  const rec = ds.record.getRecord(id)
  doSearch(rec, query)
})

```

**Comment by yasserf** [comment]
Hey Ronag,

This is interesting, however I unfortunately don't think we'll be implementing it as it won't be able to be used via a deepstream init via config.

The solution I would have used is pretty much the same as what you done. We are toying around with the idea of mapping, allowing data to be added to a record. But still really early days.

Will keep this open as an epic for tracking.

**Comment by yasserf** [comment]
Also, this should be under client! =D
