### ISSUE TITLE
Subscribe leaks out actual data reference

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#202]
I noticed while doing the exact opposite, i.e. removing necessary deepCopy, that `subscribe` actually leaks out `_$data` instead of calling `this.get()`.

https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/src/record/record.js#L191

```javascript
				args.callback( this._$data );
```

should be:

```javascript
				args.callback( this.get() );
```

**Comment by yasserf** [comment]
good catch! wana raise a pr?
