### ISSUE TITLE
discard/delete data race when quickly re-subscribing

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#204]
Because in most cases it is not. Currently I have an application where often a record is discarded before it receives the initial value and I'm spammed with these errors.

**Comment by yasserf** [comment]
Discards only get sent out once the record is actually ready:
https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/src/record/record.js#L237

You can always filter out unsolicited messages in the error callback handler.

**Comment by ronag** [comment]
If that's the case, why do I keep getting those errors?

**Comment by yasserf** [comment]
No idea, is the action a READ?

**Comment by ronag** [comment]
@yasserf: I would suppose so, doesn't `{topic: 'R'}`  mean that it's a read?

**Comment by yasserf** [comment]
Nope, Topic means its either a record, rpc or event.

You can a brief overview into the message structure [here](https://deepstream.io/info/protocol/message-structure-overview/)

**Comment by ronag** [comment]
@yasserf: Ok this is confusing me. Basically this is what happens:

```
Object {error: "media/cirm25j5f00mi3k5i8v288v0o", event: "UNSOLICITED_MESSAGE", topic: "R"} "Deepstream Error."
Object {error: "media/cirm25j5f00mi3k5i8v288v0o", event: "ACK_TIMEOUT", topic: "R"} "Deepstream Error."
Object {error: "media/cirm25j5f00mi3k5i8v288v0o", event: "RESPONSE_TIMEOUT", topic: "R"} "Deepstream Error."
Object {error: "media/cirm25j5f00mi3k5i8v288v0o", event: "MULTIPLE_SUBSCRIPTIONS", topic: "R"} "Deepstream Error."
Object {error: "media/cirm25j5f00mi3k5i8v288v0o", event: "ACK_TIMEOUT", topic: "R"} "Deepstream Error."
```

There are things going on between those message but that is basically when I get from that specific record after using our web app for 10 seconds.

**Comment by ronag** [comment]
Using a discard delay resolves the issue:

```javascript
setTimeout(() => rec.discard(), DISCARD_DELAY)
```

**Comment by ronag** [comment]
The unsolicited message is an ack message, which partly explains the following warnings.

**Comment by ronag** [comment]
I've added logging to `getRecord` (add) and `_removeRecord` (remove).

![screen shot 2016-08-09 at 14 22 03](https://cloud.githubusercontent.com/assets/3065230/17516035/5b3bd46c-5e3c-11e6-80c1-6c59dcfada7d.png)

**Comment by ronag** [comment]
ok, after some more debugging I think the problem is here at record-handler.js@278:

```javascript
RecordHandler.prototype._onDestroyPending = function( recordName ) {
	var onMessage = this._records[ recordName ]._$onMessage.bind( this._records[ recordName ] );
	this._destroyEventEmitter.once( 'destroy_ack_' + recordName, onMessage );
	this._removeRecord( recordName );
};
```

`_removeRecord` should be called through either `discard` or `delete`, which are guaranteed to be called after `whenReady`, i.e. line 278 should be removed.

**Comment by ronag** [comment]
If the record is removed from the records list on `destroyPending`, how is the `_discardTimeout` ever cleared?

**Comment by ronag** [comment]
Feels like. There is a data-race somewhere.

**Comment by ronag** [comment]
This is taking more time than I have. For now we never discard or delete any records.

**Comment by yasserf** [comment]
Can you confirm what version of the client your using?

**Comment by ronag** [comment]
1.0.2

**Comment by ronag** [comment]
This is not urgent for us. The workaround for us us implementing our own asynchronous `getRecord` which waits if the same record was recently discarded.

**Comment by yasserf** [comment]
Yeah, it's just odd because I thought this fix replicated and fixed in 1.02:

https://github.com/deepstreamIO/deepstream.io-client-js/blob/23f8fe1c50e967e693388a87a91cd3eb21f4b7f6/src/record/record.js#L237

https://github.com/deepstreamIO/deepstream.io-client-js/blob/23f8fe1c50e967e693388a87a91cd3eb21f4b7f6/test-e2e/specs/recordSpec.js#L270

I don't have much time for this either right now given the listen story, but will try get an e2e to replicate it sometime soon.

**Comment by ronag** [comment]
@yasserf: From my understanding of the code I don't see how those two commits fix this issue. I don't think this is the same case as the test is testing for.

Let's touch back on this at a later time when we both have more time. I haven't been able to reproduce this outside from our rather complex app logic.

**Comment by yasserf** [comment]
Your right, I was having a slow moment. That fix actually stopped an error from happening rather than an unsolicited message.

Yeah, let's revisit this again in a bit

**Comment by ronag** [comment]
For future reference here is our workaround:

```javascript
const slots = new Map()

function getRecord (recordName, cb) {
  let slot = slots.get(recordName)

  if (!slot) {
    slot = {
      record: ds.record.getRecord(recordName),
      pending: null,
      refs: 0
    }
    slots.set(recordName, slot)
  }

  slot.refs += 1

  if (slot.pending) {
    slot.pending.push(() => cb(slot.record))
  } else {
    cb(slot.record)
  }
}

function discardRecord (recordName, cb) {
  const slot = slots.get(recordName)

  slot.refs -= 1

  if (slot.refs !== 0) {
    return
  }

  slot.pending = []
  slot.record.on('discard', () => {
    if (slot.refs === 0) {
      slots.delete(recordName)
    } else {
      slot.record = ds.record.getRecord(recordName)
      slot.pending.forEach(cb => cb(slot.record))
      slot.pending = null
    }
  })
  slot.record.discard()
}
```

**Comment by ronag** [comment]
@yasserf: here is a reproducible case:

```javascript
var deepstream = require('deepstream.io-client-js')

var ds = deepstream(`localhost:6021`)
  .login({}, (success, authData) => {
    if (!success) {
      console.error({ authData }, 'Deepstream Authentication Failed. Shutting down...')
      setTimeout(() => process.exit(1), 500)
    }

    main()
  })

ds.on('connectionStateChanged', connectionState => {
  console.log({ connectionState }, 'Deepstream Connection State Changed.')
})

ds.on('error', (error, event, topic) => {
  console.error({ error, event, topic }, 'Deepstream Error.')
})

function main () {
  for (let i = 0; i < 512; ++i) {
    let rec = ds.record.getRecord('tmp/' + i % 128)
    rec.set({
      asd: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.'
    })
    rec.discard()
  }
  setTimeout(main, 10)
}
```

**Comment by ronag** [comment]
@yasserf: bug

**Comment by yasserf** [comment]
Closing. This should be fixed in V4 due to the subscribe/discard timeout buffer.
