### ISSUE TITLE
Calling `set` in `subscribe` callback can cause some confusing results

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#215]
Calling  `set` inside a callback invoked through `completeChange` can cause very confusing results since the next callback invocations would see different data than at the beginning of `completeChange`.

I think the fix for this is to make sure to emit all change events asynchronously, i.e.

```javascript

		if( currentValue !== this._oldPathValues[ path ] ) {
			setTimeout( this._eventEmitter.emit.bind( this._eventEmitter, path, currentValue ), 0 );
		}
```

This makes sure that all callbacks are invoked with the correct *values* and correct *order*, *before* any call to `set`.

However, applying this change breaks a lot of tests.

**Comment by yasserf** [comment]
Hey, a similar issue was actually raised against the server a few days ago! That causes a crash though on the client dude to shared state and recursion. I think there might be a cleaner solution since setting timeouts might be a little expensive.

Can you provide an example of something that works but is currently confusing?

**Comment by ronag** [comment]
An alternative to setTimeout would be using something like the deferred method queue.

Here is something that is confusing:

```javascript
var rec = ds.record.getRecord('foo')

rec.subscribe('a', function (value) {
  console.lob('a', value);
  rec.set('a.b', 2);
});

rec.subscribe('a.b', function (value) {
  console.lob('a.b', value);
});

rec.set('a.b', 1);
```

But basically, the issue here is that `_beginChange` can be called again before `_completeChange`.

**Comment by ronag** [comment]
Maybe something along the lines of:

```javascript
	if( !this.isReady || this.isChanging ) {
		this._queuedMethodCalls.push({ method: 'set', args: arguments });
		return this;
	}
```

**Comment by ronag** [comment]
It's difficult to get my head around exactly in how many ways things could go wrong. The only thing I'm sure of is that things can go very wrong with the current way it's handled.

**Comment by ronag** [comment]
I would suggest we use `setTimeout` for now, for correct behaviour and then later optimize it once we've figured it out...

**Comment by ronag** [comment]
part of general async race issue
