### ISSUE TITLE
Check for invalid paths

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#219]
Breaking out from #214. 

Json paths should be checked for validity. Currently the behaviour for invalid paths is pretty much undefined.

**Comment by yasserf** [comment]
I would probably suggest we deprecate our path notation (which is built around our random thing) and use a third party library like jsonpath. Only issue is its almost 7000 lines, so might be just add an option in V4 to allow custom JSON path libraries. 

This would need to be used in both the server and JS, but the server can easily take the extra 80kb weight as a dependency.

**Comment by yasserf** [comment]
Yeah I’m still 100% for getting rid of our custom paths and using an actual json path implementation. raising this as a V5 issue

**Comment by yasserf** [comment]
Closing in favour of https://github.com/deepstreamIO/deepstream.io/issues/1046
