### ISSUE TITLE
Passing multiple urls for failover?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#225]
I remember it being mentioned that the client would be able to failover to other servers. Which I assume would require the user to pass multiple server urls to the client. However, looking through the different PRs and branches I can't see anything along those lines? Am I missing something?

**Comment by ronag** [comment]
Also, do you guys have any experience with using a reverse proxy (tcp and/or http) as a failover mechanism?

**Comment by yasserf** [comment]
It's something we will look into now we have cluster awareness in 1.1 release.

**Comment by WolframHempel** [comment]
In regards to reverse proxies, please find more here
https://deepstream.io/tutorials/integrations/other-nginx/

**Comment by yasserf** [comment]
We would recommend putting deepstream behind a load balancer for now. To failover between multiple regions isn’t possible doing that but we haven’t had any use cases where that was needed yet.
