### ISSUE TITLE
emit closed event once all ACKs are received

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io-client-js#236]
Following this conversation on the slack channel

iiridayn [8:12 PM]  
@wolframhempel I agree, which I why I traced down the issue with debugging statements in the client and server code, instead of increasing timeouts :stuck_out_tongue:. This is how I know the client appears to have been starved of reading the ACKs from the server - I'm still considering how to design the bulk password hashing using node to not block the event loop - I'm leaning towards the messy callback chain.

I do in parallel open a deepstream server connection and read lots of data from a SQL database (about 300 M when it was JSON files). However, the part which triggered the ACK timeouts was a loop over 200+ user records, creating a deepstream record, then converting the SQL sourced data (including rehashing passwords, which is meant to be slow for entropy stretching, and is therefore slow), then `set`ting that to the record, waiting for `whenReady`, then `discard`ing the record. Debug statements in the client and server source code revealed that the server was getting all messages and replying, but the client was not receiving any messages, and stopped sending at 99 (there was also a request to the search provider for current users, making it 100).

So - to reply to your question, I know that the client started queuing and not sending outgoing messages, and that while it was still awaiting incoming messages, I'd managed to starve the nodejs event loo and prevented reading the socket connection. I'm still researching how to prevent that, but for now precomputing the password hashes before the record create/set/discard loop has prevented the record creation ACKs from getting delayed, and there are no other delays triggered. As I said, still reading about how to not starve the event loop - it's looking like I'll need a log of calllbacks. That first was more informational, and a celebration that I'd traced the bug I was experiencing.

My _other_ question was completely unrelated. I'd like a way to know when there are no expected in flight `discard` ACKs, so I can wait for them before calling `deepstream.close()`, so deepstream doesn't complain about receiving packets on a half closed socket.

----- Today September 3rd, 2016 -----
wolframhempel [11:16 AM]  
@iiridayn thanks for clarifying and tracking down the issue to the event loop, that makes a lot of sense. As mentioned, like most performance focused protocols deepstream is based on eventual consistency and NACKs for writes - negative feedback if something went wrong, rather than acknowledgement of everything successful. As you've said though, more substantial operations are acknowledged and deepstream does queue messages to prevent package loss when the socket isn't writable. I agree that a callback / final `closed` event once all ACK timeouts are cleared would make a lot of sense, I'll raise an issue

**Comment by WolframHempel** [comment]
This is somewhat related to #232

**Comment by yasserf** [comment]
We fixed this in 2.1.2 by doing the following:

on connection disconnects, clear all timeouts
on receiving an ack that we no longer care for, don't raise an error ( its not an error )

The rest of this issue is around closing protocols where we can guarantee all in flight messages have been processed.
