### ISSUE TITLE
Implement records as FSM?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#241]
I don't have any experience with this myself but I thought I'd share the thought. In order to resolve some of the async issues in terms of records I believe it might be a good idea to model records in terms of a FSM. In which case a library such as https://github.com/ifandelse/machina.js might be something to look into.

Initial thoughts or comments on that?

**Comment by AlexBHarley** [comment]
We currently use binary flags to indicate record states, but we'll be looking to at least generating a FSM diagram showing record states and transitions
