### ISSUE TITLE
Providers for records stop handling new clients once all subscribers discard the record

### ISSUE THREAD

**Issue by raymond-h** [deepstreamIO/deepstream.io-client-js#253]
Once all other clients that were subscribed to a record have discarded a record that a provider was providing info to, the provider will have its callback called with `isSubscribed` as false. However, when new clients request the same record, the provider no longer gets information that there are no subscribers.

Example code:
```js
// one.js
var Deepstream = require('deepstream.io-client-js');

var client = Deepstream('localhost:6021').login({});

var iid = null;

client.record.listen('cool/.+', (match, isSubscribed, response) => {
	console.log(match, isSubscribed, response);
	
	if(isSubscribed) {
		response.accept();

		var r = client.record.getRecord(match);

		iid = setInterval(() => r.set('random', Math.random()), 1000);
	}
	else {
		client.record.getRecord(match).discard();
		clearInterval(iid);
	}
});
```

```js
// two.js
var Deepstream = require('deepstream.io-client-js');

var client = Deepstream('localhost:6021').login({});

var r = client.record.getRecord(process.argv[2] || 'cool/banana');

r.subscribe(console.log);

setTimeout(() => {
	r.discard();
}, 4000);
```

Run `one.js` once, and `two.js` multiple times with NodeJS. As soon as all `two.js` clients discard the record `cool/banana`, `one.js` has its callback called to let it know the record has no subscribers, but when you start `two.js` clients again, `one.js`'s callback isn't called with `isSubscribed` as `true` anymore.

Unlistening and relistening after no clients are subscribed anymore does not seem to work either.

**Comment by yasserf** [comment]
Hey Raymond, I just ran into this issue yesterday as well. Thank you for the reproducible code! Will be looking to fix it asap.

**Comment by yasserf** [comment]
I think this instance might be since you calling discard incorrectly, keep a reference to the record created in is subscribed and discard that in issubscribed=false.

Well update with a code sample as soon as I get behind a real computer!

**Comment by raymond-h** [comment]
Actually the exact same issue occurs even if the instances of `two.js` are killed instead of explicitly discarding the record as well. Forgot to mention that, sorry!

**Comment by yasserf** [comment]
@raymond-h Regarding your code, can you try:

```
// one.js
var Deepstream = require('deepstream.io-client-js');

var client = Deepstream('localhost:6021').login({});

var iid = null;

client.record.listen('cool/.+', (match, isSubscribed, response) => {
    console.log(match, isSubscribed, response);

   var r;
    if(isSubscribed) {
        response.accept();

        r = client.record.getRecord(match);

        iid = setInterval(() => r.set('random', Math.random()), 1000);
    }
    else {
       r.discard(); <-- changed
        clearInterval(iid);
    }
});
```

You are discarding a record immediately after requesting it, which puts the listening in a weird state, instead only call `getRecord()` once in the entire closure

**Comment by raymond-h** [comment]
Oh, that does work properly - now I feel a bit silly, hahah. I think I was assuming records were only fetched to client once, and when the same record was asked for multiple times, it would just return the existing client-side instance for the record. But I see in the source code that it also keeps a reference count, which would explain the weirdness going on.

**Comment by yasserf** [comment]
Yeah, the way it works in the client is everytime `getRecord` is called it ups the usage by one. That way the server only has to know about when a client is subscribed and the client is responsible for dealing with the subscription lifetime. If the connection drops the client then only has to send a single resubscribe event to the server as well which makes failover less resource intensive.

There is an issue in listening still, unfortunately it happens very rarely and has something to do with connection states going wierd and not notifying the server that it closed correctly. We are going to be moving towards a pure websocket approach which has heartbeats and should fix this, don't want to invest alot of time into the issue until then.

Eitherways though, you got listening spot on otherwise!

You happy if I close this issue?

**Comment by raymond-h** [comment]
That's alright, I'll close it myself. Thanks!
