### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by jensvdh** [deepstreamIO/deepstream.io-client-js#256]
Does this library have Typescript typings? If not I'd love to contribute to this project by building them and opening a PR.

**Comment by yasserf** [comment]
It currently does not, but that would be awesome if you do!

**Comment by jugglingcats** [comment]
@jensvdh did you get anywhere with this?

**Comment by jensvdh** [comment]
@jugglingcats I have gotten a bit busy with work. But I should have a PR with Typescript typings up over the next week.

**Comment by stemcc** [comment]
@jugglingcats You could always gist what you've got so far and perhaps the community can take it the rest of the way.

**Comment by RichiWIP** [comment]
I have created a quick d.ts to use in a current project of mine. Hope this helps.
https://gist.github.com/RichiWIP/691235f5257e014b3e8a040dfe247187

**Comment by jensvdh** [comment]
Hi @RichiWIP. Awesome work! I just tested the definitions locally and they seem to work great for the most part. Although the presence API seems to be missing.

I went ahead and created a pull request here

https://github.com/deepstreamIO/deepstream.io-client-js/pull/283

This should bundle the typings with this repository, making it near automatic for TS developers to get started.

**Comment by benjaminVadon** [comment]
Hi all,
I'm pretty a new to typescript and I'm attempting to do something like that using the d.ts file provided by @RichiWIP 
```
client.on("connectionStateChanged", function (state: ConnectionState) {
            switch (state) {
                case ConnectionState.OPEN:
                    console.log("open");
                    break;
                default:
                    console.log("not open");
            }
      })
```

Doing so, webstorm suggests me to import enum this way
`import ConnectionState = deepstreamIO.ConnectionState;`

In typescript there is no problem, enum is well recognize, but after bundled all in JS file, and then open it  with chrome, it complains that 
> VM396:1 Uncaught ReferenceError: deepstreamIO is not defined

I've attempted many differents things (other kind of import, adding export in enum, change deepstream export object), probably insane for a typescript pro dev, that I'm not yet.

I've already searched in ts documentation, github, google about namespace, module, enum, ambient context,... and can't find a way to achieved that.
So, is it possible to use enum declared d.ts ? and if yes, can you help me or drive to the right place to learn ?

**Comment by jensvdh** [comment]
Hi.

There's a pull request open for the Typescript definitions.

Can you try installing this specific branch from NPM until it's been merged in?

https://github.com/deepstreamIO/deepstream.io-client-js/pull/283

It looks like you didn't import the Deepstream Library properly.

There are instructions in the readme file:
https://github.com/jensvdh/deepstream.io-client-js/blob/93e701dfa95dd3e008d289331d84b18f1bd2b91b/README.md

**Comment by benjaminVadon** [comment]
So, first thank you for you quick reply.
I didn't know that npm allow this stuff, pretty cool in fact !

I did it like you ask me to do and I also removed the type file from my typings directory
The same problem happens in js compiled version.
One difference is, if I remove 
```    
"typeRoots": [
      "./node_modules/deepstream.io-client.js/src/client.d.ts"
    ]
```
typescript doesn't complain and is able to find typing file.

If you want I can upload files of my test project.

**Comment by jensvdh** [comment]
So it looks like we are halfway there. The compiler seems to have picked up the typings. So that's a good start.

Can you send me a github gist of your code?

**Comment by benjaminVadon** [comment]
there it is, nothing fantastic :
[simple gist](https://gist.github.com/benjaminVadon/0c4292b93b9ef033a7cff3b15b774dbc)

**Comment by jensvdh** [comment]
Yep. Seeing the same issue on my end. Let me investigate and get back to you. :)

**Comment by jensvdh** [comment]
Looks like there are a few issues with the way the typings are declared. The deepstream object wasn't exporting the ENUMS with the constants properly. This can be fixed by changing the index.d.ts file like this:

` interface deepstreamStatic {
                CONSTANTS: {
                        CONNECTION_STATE: ConnectionState
                }
                MERGE_STRATEGIES: {

                }
                (url: string, options?: Options): deepstreamQuarantine;
        }`

You should then be able to reference the connection states like
`import * as deepstream from 'deepstream.io-client-js'
`const CONNECTION_STATE = deepstream.CONSTANTS.CONNECTION_STATE`

avoid referencing that DeepstreamIO namespace. I'm not sure why it's there. It should probably be cleaned up.

**Comment by benjaminVadon** [comment]
Yeah thank you !
I will do this and add other enums the same way in your pull request.

**Comment by benjaminVadon** [comment]
In fact I was reacting to quickly...
Typescript compiler doesn't find  properties of enum. 
By using that : 
`CONNECTION_STATE.OPEN`
compiler respond
`(20,60): error TS2339: Property 'OPEN' does not exist on type 'ConnectionState'.`

if I  change to this
`CONNECTION_STATE.toString(6)`
Compilation works, and I can access to  properties this way 
`deepstream.CONSTANTS.CONNECTION_STATE.OPEN`

**Comment by jensvdh** [comment]
I think typescript generates integers for enum's vs Strings. So we may have to use a different datastructure: https://www.typescriptlang.org/docs/handbook/enums.html

**Comment by jensvdh** [comment]
@RichiWIP , any input on this? Did you get those enums to work?

**Comment by benjaminVadon** [comment]
Finally, I didn't managed to use deepstream's Constants by this way, but I can access them by the client object obtained with deepstream("url").
It's enough for my current simple usage, so @jensvdh the way you advise me to change d.ts is a better form than original, but is it a good way for a library, and mainly do you want I apply this change in your pull request ? (and for other constants too?)

By the way, thank you for your help !

**Comment by benjaminVadon** [comment]
@jensvdh and @RichiWIP  any advice on this point finally ?

By usage, it's not so bad  to access these constants by a client object, and as far better than nothing, as it is in current master, for new comers to deepstream.

I added Event, but no others because values don't match names, e.g. `exports.TYPES.NUMBER = 'N';` in js code. 
The changes to apply are  (I didn't found the right way to update your pull request):
```
    interface deepstreamStatic {
        CONSTANTS: {
            CONNECTION_STATE: ConnectionState,
            EVENT : Event
        }
        MERGE_STRATEGIES: {

        }
        (url: string, options?: Options): deepstreamQuarantine;
    }
```

**Comment by yasserf** [comment]
Closing this issue for now as we have merged the typescript in. I may have missed something thats missing, in which case it would be great if we can specifically mention what it is. Thanks!

**Comment by jacobbogers** [comment]
awesome lib, are there plans to do full typescript version?
