### ISSUE TITLE
AnomynousRecord is missing whenReady event

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io-client-js#26]
The AnomynousRecord should raise a whenReady event to have the same behaviour as a normal Record.

It's worth noting that since setName effectively changes the record used underneath which means whenReady can be called more than once, which should be explicitly stated in the docs.

**Comment by yasserf** [comment]
I'm still a bit edge on implementing this with the premise of whenReady being called multiple times.

We could call the method.. whenReadyMultipleCallbacks() * we won't, but like, explicitness? *

**Comment by WolframHempel** [comment]
Let's proxy the underlying record's ready event, but a whenReady method doesn't really make sense in this context

**Comment by yasserf** [comment]
Fixed
