### ISSUE TITLE
I can't connect with server

### ISSUE THREAD

**Issue by bay007** [deepstreamIO/deepstream.io-client-js#260]
I follow the basic tutoria for connect with server, I have W7, I ran deepstream.exe.
I tried with client code with oficial CDN client sript.
![oficialcdn](https://cloud.githubusercontent.com/assets/8164038/19416417/35f84656-9355-11e6-8245-284738e7dff6.PNG)
I am having the next error 
![error](https://cloud.githubusercontent.com/assets/8164038/19416424/778df3cc-9355-11e6-8cd8-1bc64764b11c.PNG)
Everything is running on localhost.

I search on github sript, I found a previous version (20d2e36bb26b7396074c7e956292222774669d8c) [https://github.com/deepstreamIO/deepstream.io-client-js/commit/20d2e36bb26b7396074c7e956292222774669d8c](url)
I installed previous version in local file named deepstream.js; I refer my html code to this local file as follow:
![localscript](https://cloud.githubusercontent.com/assets/8164038/19416442/086f91f2-9356-11e6-914c-e197d0a331da.PNG)

Tried again to connect, and every works!!!!; Only change the version of deepstream.min.js version earlier.
![no errors](https://cloud.githubusercontent.com/assets/8164038/19416450/616db54a-9356-11e6-81ca-276b82abe9bc.PNG)

**Comment by yasserf** [comment]
Hey @bay007 

The master branch now uses websockets instead of engine.io, which is why requiring it from the master branch does not work against the last release version

We'll be releasing an RC candidate soon!

**Comment by yasserf** [comment]
Is this still an issue?
