### ISSUE TITLE
Return promises when no callback is provided

### ISSUE THREAD

**Issue by deadbeef84** [deepstreamIO/deepstream.io-client-js#261]
It would be nice if both node.js style callbacks and promises were supported. A common method many liraries use to support this is to return promises when no callback is provided. I saw #22, and I understand the performance concern and having two separate APIs to maintain doesn't seem feasible. Using this opt-in method shouldn't affect performance too much, and there wouldn't be a separate library to maintain.

Here's an untested example implementation

``` js
// Helper method
function createPromise() {
  var callback = null;
  var promise = new Promise(function(resolve, reject) {
    callback = function(err, value) {
      if (err) {
        reject(err)
      } else {
        resolve(value);
      }
    };
  });
  promise.callback = callback;
  return promise;
}

// Usage
function snapshot(recordName, callback) {
  var promise;
  if (typeof callback === 'undefined') {
    promise = createPromise();
    callback = promise.callback;
  }
  // implementation as is today, just call callback(err, value)
  return promise;
}
```

I can see 3 potential issues with this adjustment:
- The return value for functions with callbacks would always have to be a promise or undefined. Not sure if any of the functions currently use the return value for something else.
- The resolved value would have to be a single value, for the callback it can be multiple parameters. This would be possible to solve by resolving the promise using an array or object.
- Making callback optional may create problems when other parameters are optional, though I don't think that's an issue for the deepstream api.

Please let me know what you think. I would be willing to help implement this if you're interested.

**Comment by yasserf** [comment]
Hey @deadbeef84,

This def makes sense for APIs like `snapshot`, `whenReady` and all RPCs.

We don't use transpiling ( if we did we would change the code quite a bit ) so native promises are currently not really an option.

Out of curiosity, do you have any experience with the bluebird [promisify](http://bluebirdjs.com/docs/api/promise.promisifyall.html) api? That approach might also be a quick win, and is similar to aws sdks for example.

**Comment by ronag** [comment]
An even simpler way to do it:

```javascript
function snapshot(recordName, callback) {
  if (typeof callback === 'undefined') {
    return new Promise((resolve, reject) => this.snapshot(recordName, (error, value) => error ? reject(error) : resolve(value))
  }
}
```

**Comment by AlexBHarley** [comment]
You can use promisify the same way as example the AWS sdks recommend. We don't want to bundle this into the js client directly. Any suggestions on how we can do it with web pack/browserify?

**Comment by serle** [comment]
The new ES7 async / await with exceptions pattern (as opposed to promises) would simplify the user land experience significantly.

**Comment by yasserf** [comment]
This needs to land in the next release

The one issue we are facing is due to the signature of the `ready` callback, since it does not follow node convention with an error type. 

We can solve this by having a backwards compatible check that looks if the callback provided has two arguments and assume the first one is an error ( yaay magical angular-like solutions ).

Or we can just treat the callback version as it is, and if no callback is provided use the correct

.then
.catch 

approach
