### ISSUE TITLE
Add to CDNJS

### ISSUE THREAD

**Issue by jdmnd** [deepstreamIO/deepstream.io-client-js#263]
Currently we support the deepstream client using the rawgit CDN. 
We should investigate moving to another CDN that provides static hosting for individual deepstream releases, such as [cdnjs](https://github.com/cdnjs/cdnjs).

**Comment by jdmnd** [comment]
https://cdnjs.com/libraries/deepstream.io-client-js

**Comment by yasserf** [comment]
So cool!
