### ISSUE TITLE
2.0 build with webpack

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#264]
```
./~/ws/lib/WebSocketServer.js
Module not found: Error: Cannot resolve module 'tls' in /node_modules/ws/lib
resolve module tls in /node_modules/ws/lib
```

**Comment by yasserf** [comment]
Interesting. Does this mean ws is not webpack compatible?

**Comment by ronag** [comment]
@yasserf: Well it's possible to get it to work. I still haven't figured out how to get rid of all the warnings.

**Comment by ronag** [comment]
@deadbeef84: Paste your solution here.

**Comment by deadbeef84** [comment]
It appears `ws` is only meant for node, not for usage in the browser - which makes sense as it is a websocket implementation :)

With webpack it can be fixed quite easily, just add the following to your configuration:
```js
externals: {
  ws: 'WebSocket'
},
```
This essentially replaces `var ws = require('ws')` with `var ws = WebSocket`.

**Comment by yasserf** [comment]
yeah that makes sense, we have the equivalent for browserify:

`ignore: [ 'ws' ]`

Anyone interested in committing a fix?

**Comment by deadbeef84** [comment]
The solution I posted is a client side webpack configuration, I'm not sure how to fix it in the library itself. I guess you would have to create a bundle that excludes the require('ws') and make webpack/browserify use that?

**Comment by yasserf** [comment]
Believe this should be fixed in last commit. Be great if you let me know, tested it via `test-webpack` and it seemed fine

**Comment by AlexBHarley** [comment]
Could someone verify if this is fixed? @ronag

**Comment by yasserf** [comment]
This appears to be working when tested again with 2.1.1
