### ISSUE TITLE
Doesn't support component-emitter 1.2+

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#265]
I'm getting breaking changes since we depending on the internal `_callbacks` property of the component-emitter.

Better to simply do it inline and avoid weird bugs...

https://github.com/nxtedition/deepstream.io-client-js/commit/406bf89df025f64d875ae7a17a5e7576caf8569b

**Comment by yasserf** [comment]
Nothing has changed in record class for a while now. Are those breaking changes breaking due to changes in your fork?

**Comment by ronag** [comment]
It's because I've removed exact versioning on `component-emitter`. This commit https://github.com/component/emitter/commit/b34d74c7aeef326eeb452a3713b06ad20f92ebb4 breaks deepstream.

**Comment by yasserf** [comment]
This is something I want to look at, but it seems we use callbacks in events and records as well.

Is there anything useful that came out in the new emitter releases?
