### ISSUE TITLE
can't connect or get any data using angular or even using a normal connection

### ISSUE THREAD

**Issue by heshamelmasry77** [deepstreamIO/deepstream.io-client-js#267]
![image](https://cloud.githubusercontent.com/assets/15607302/19726638/2821a646-9b8c-11e6-9a5a-5a3ad3d0cd3c.png)

Hey that's the error i am getting when i try to connect and get data.

i am using angular to do that and here is my app.js code i really don't know what is the problem struggled a lot : 

```

var app = angular.module('myApp', []);



app.service( 'deepstream', function() {
    var client = deepstream('deepstreamer.herokuapp.com:80',{
  rpcAckTimeout: 50000,
  recordReadTimeout: 50000,
  rpcResponseTimeout: 50000,
  subscriptionTimeout: 50000,
  recordReadAckTimeout: 50000
}).login();
    return client;
})

var vm = this;

app.controller( 'myCtrl', function( deepstream, $scope ) {

var list = deepstream.record.getList('exceptions/131976');

    list.subscribe(function( entries ){

        vm.myCtrl = entries.map(function( entry ){
            vm.data = deepstream.record.getRecord( entry );
            vm.data.subscribe( scopeApply );
            return vm.data;
        });

        scopeApply();
    });


});
```

so all what i wanted to do is to read my json data coming from deepstream and present it using angular like how i do with a normal json file for example : 

```

var vm = this;


app.controller('myCtrl',['$scope', '$http', function($scope, $http){
$http.get('json/data.json')
    .then(function (response) {
//    console.log(response.data);
        vm.data = response.data;
    });

}]);
```

**Comment by yasserf** [comment]
Hey,

Can you tell me what versions your using? Master is currently v2 which isn't backwards compatible with released versions.

**Comment by WolframHempel** [comment]
By default deepstream.io listens to port 6020 - did you configure it to use
Heroku 's port?
