### ISSUE TITLE
Optimisation - Don't read from server if client overwrite value

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#269]
In the case where the client will directly overwrite the entire record, reading it back from the server is kind of unnecessary.

``` javascript
const rec = ds.record.getRecord('foo')
rec.set({ overwrite: true })
```

We could then wait for the next tick before deciding to send `READ` or just `UPDATE` with a `SUBSCRIBE` if the record is still active.

**Comment by yasserf** [comment]
Problem with this is we still need the head in order to a write and we don't have this log. It definitely is a huge improvement but its for a very specific use case so I don't think we will be implementing this
