### ISSUE TITLE
Why use Math.random() to generate Uid?

### ISSUE THREAD

**Issue by layanto** [deepstreamIO/deepstream.io-client-js#280]
Why is deepstream.io-client-js using Math.random() to generate Uid? Not sure if this article is still true (https://medium.com/@betable/tifu-by-using-math-random-f1c308c4fd9d#.unnyhs2yg) but it claimed that with Chrome's v8 Math.random() implementation, there is 50% chance of collision with just 30,000 iterations. I understand because client.getUid() prefix the Uid with timestamp in millisecond, collision can only happen if a large number of Uid-s are generated within the same millisecond but this is possible on heavily loaded system scaled horizontally across multiple servers.

Why not use window.crypto.getRandomValues?

**Comment by layanto** [comment]
Looks like the issue with Math.random in Chrome was fixed relatively recently earlier this year in Chrome 49.

http://v8project.blogspot.com.au/2015/12/theres-mathrandom-and-then-theres.html?m=1

I still think should use crypto rng to generate higher quality Uid.

**Comment by ronag** [comment]
I think the entropy is enough for what deepstream is using it for. If you want to have shorter uuids with better entropy see: 

https://github.com/nxtedition/xuid/blob/master/index.js
https://github.com/ericelliott/cuid
https://github.com/dylang/shortid

**Comment by layanto** [comment]
Deepstream Java Client is using java.util.uuid to generate UUID v4 in getUid() function. So if you have an application with both java and javascript clients, they will generate records with different format id. Java.util.uuid class is generating UUID using cryptographically secure random number generator like javascript's window.crypto.getRandomValues.

**Comment by yasserf** [comment]
That's a good point. We should change the java client to use the same algorithm as the JS one for consistency since JS client has been in production much longer.

In terms of clashes, the possibility of a clash vs the time needed to create a cryptographically secure random number is the offset we need to take into consideration. `crypto.getRandomValues` is great but we support IE9+ which means we can't actually use it for the near future.
