### ISSUE TITLE
json-path -> patch: TypeError: Cannot read property of null

### ISSUE THREAD

**Issue by cristiano-belloni** [deepstreamIO/deepstream.io-client-js#281]
Hello,
This happens in `v2.0.0`, but not in `1.0.0` (I discovered the issue after upgrading). The culprit seems to be the `patch` function in the `record/json-path.js` module, and the issue seems to have been introduced in [this commit](https://github.com/deepstreamIO/deepstream.io-client-js/commit/f687485a420b77e9d1922e6032f4b3524dab042b).

My particular case is kinda complex, but debugging the client it seems that this exception gets thrown when `patch` is called by  `set` and a value lower in the tree goes from falsy (or possibly even non-object) to object. 

In my case, `oldValue` is descended recursively in patch, until it gets to a sub-object of the form:

**oldValue**
```javascript
{
  job: null,
  joinedAt: 1480020987915
}
```

**newValue**
```javascript
{
  job: { id: 88 },
  joinedAt: 1480020987915
}
```

**deepCopy**
```javascript
true
```

At this point, `patch` is recursively called with the `job` sub-object, and the arguments are:

**oldValue**
```javascript
null
```

**newValue**
```javascript
{ id: 88 }
```

**deepCopy**
```javascript
true
```

This makes the client crash with an exception, when [this line](https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/src/record/json-path.js#L97) is executed:

```javascript
obj[ props[ i ] ] = patch( oldValue[ props[ i ] ], newValue[ props[ i ] ], deepCopy )
```

Since `props` is the keys of `newValue`, this will try to compute `oldValue.id`. But `oldValue` is `null` and an exception gets thrown. It seems that an additional check for this (pretty common) case is needed in `patch`.

**Comment by yasserf** [comment]
Hey @cristiano-belloni,

Thank you for the detailed log! We will add this in for the next release

**Comment by gpresland** [comment]
Having this exact same issue but using the client
```
"deepstream.io-client-js": "^1.1.1",
```
and the server `1.1.0`.

**Comment by cristiano-belloni** [comment]
@gpresland I temporarily worked around this issue by replacing all the `null` values with empty objects.

**Comment by ronag** [comment]
I don't see how `oldValue` can be null inside the  `!Array.isArray( newValue ) && typeof oldValue === 'object' && typeof newValue === 'object'` clause?
