### ISSUE TITLE
v2.0.0 or v1.1.0 in min.js?

### ISSUE THREAD

**Issue by hipkiss91** [deepstreamIO/deepstream.io-client-js#300]
In the deepstream.min.js file it states the version is v1.1.1 but the commit says the version is v2.0.0. Please can someone clarify which one it is? 
https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/dist/deepstream.min.js

**Comment by yasserf** [comment]
Hey @hipkiss, thank you for rinsing this. It should be 2.1 now!

@alex-harley
