### ISSUE TITLE
Signal errors after log in fails

### ISSUE THREAD

**Issue by ChristophConrads-deepstreamHub** [deepstreamIO/deepstream.io-client-js#302]
After a failed log in attempt, the client can keep using the API and no exceptions are thrown (or similar).

[auth-fail.zip](https://github.com/deepstreamIO/deepstream.io-client-js/files/670812/auth-fail.zip)

**Comment by yasserf** [comment]
You can use things locally still yet, but all remote syncing will be disabled. Feels more like a developers UX issue.
