### ISSUE TITLE
jsonPATH issue

### ISSUE THREAD

**Issue by edwardsmarkf** [deepstreamIO/deepstream.io-client-js#307]
the [npm jsonPath](https://www.npmjs.com/package/jsonpath) version accepts embedded periods in the key value (such as an email address), but not the DS version.

is it possible to use the npm version instead?

here is a very simple code snippit to demonstrate it:

```
    var cities = [
          { name: "London", "population": 8615246 , 'john@gmail.com' :  'johns email address' },
    ];

    var jp = require('jsonpath');

    console.log('name: ' +  '$..name' );
    console.log('email: ' +  jp.query(cities, '$..["john@gmail.com"]') );
```

**Comment by yasserf** [comment]
This will be done for V5. Closing since we have a few issues tracking it.
