### ISSUE TITLE
Possibility to send messages between WebRTC clients

### ISSUE THREAD

**Issue by gbhrdt** [deepstreamIO/deepstream.io-client-js#31]
Hi,
I haven't found anything like that in your docs, therefore I'd suggest, that one should be able to implement plain text messaging along with the video/audio streaming in calls.
Or is this already possible?

Thank you!

**Comment by WolframHempel** [comment]
Hi @gbhrdt ,

you can easily exchange text messages with other participants of a call using [deepstream's event mechanism](http://deepstream.io/docs/client.event.html). - Just create a unique event-name for your room.

This is also the reason we've decided against exposing the WebRTC data-stream API: It would duplicate exiting concepts in deepstream.

**Comment by gbhrdt** [comment]
Hi @WolframHempel 
thanks for your quick reply. Wouldn't it be much more efficient to do the sending via WebRTC data channels for big projects or for bigger data? Also, how can I easily ensure security if every other client can subscribe to any event, as well?
It wouldn't duplicate existing concepts in my opinion, as WebRTC data should be exchangeable between the clients directly.

**Comment by yasserf** [comment]
hey,

You are totally right that using WebRTC data would be more performant in applications with large data that can be shared in a P2P manner

From a permission/security aspect, you can easily apply permissions to the current event mechamism to ensure other clients can't subscribe to them, although this does require permissions to be set on the server.

We'll definitely flag this up as a feature on the roadmap, but given a large subset of the functionality is already provided in the event API ( minus the performance gains ) it isn't as high up as reliance and failover.

If you have an idea about how you would expect the API to look like that would be a great place to flesh out the work needed to implement this.

**Comment by yasserf** [comment]
This has been pushed out of scope since we want to concentrate on enhancing security, permissions and some other big features such as collections, list deltas and different clients in favor of supporting P2P connections.
