### ISSUE TITLE
new shared array and atomics API in es2017

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#318]
With the new shared array and atomics API in es2017 it should be possible to move a lot of the parsing logic into a web worker with low overhead.

**Comment by yasserf** [comment]
Sounds interesting, do you have any links you would recommend? And will it land in Node 8?

**Comment by ronag** [comment]
In node 7 it's already under the experimental flag.

**Comment by ronag** [comment]
http://www.2ality.com/2017/01/shared-array-buffer.html

**Comment by ronag** [comment]
Chrome adds support in 58. Not sure if it makes it into Node v8...
