### ISSUE TITLE
yarn?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#321]

**Comment by ralphtheninja** [comment]
?

**Comment by yasserf** [comment]
I'm missing the telepathic ability to follow this conversation! =P

**Comment by ronag** [comment]
https://yarnpkg.com

**Comment by yasserf** [comment]
Doesn't yarn install just work using package.json? Or is this about commiting a lock file? ( Not sure about best practices with yarn yet, since they don't support private github repo references =(

**Comment by ronag** [comment]
This is about the lock file.

**Comment by ralphtheninja** [comment]
I'm :-1: on commiting `yarn.lock`. This should only be done in applications imo.

**Comment by ronag** [comment]
> This should only be done in applications imo.

Then you are misunderstanding the point of yarn.lock

We currently have these dependencies:

```js
    "bufferutil": "^2.0.1",
    "component-emitter2": "^1.3.5",
    "utf-8-validate": "^3.0.1",
    "ws": "^2.1.0"
```

If any of these dependencies or (sub dependencies) are updated they can break an otherwise stable deepstream release.

**Comment by ralphtheninja** [comment]
I know the point of yarn.lock, I just don't think the trade offs are worth it on a module level

My objections are:

* you can only guarantee this for people using yarn, the rest of the npm eco system would not be affected, so you're not really guaranteeing anything
* people using yarn can still use their own yarn.lock to achieve the same effect
* you add more more thing that has to be maintained, are you prepared to maintain the lock file each time a bug fix for any of these dependencies have been released (which the non yarn users would get)?

It's not that I don't like yarn.lock, I'm just saying there are trade offs to be considered. A middle ground could be to mitigate the risk (still no guarantee) by changing `^` to `~` in the dependencies.

**Comment by yasserf** [comment]
We could use a shrinkwrap, is that both yarn and npm supported?

**Comment by ronag** [comment]
shrinkwrap is not deterministic

**Comment by ronag** [comment]
> you can only guarantee this for people using yarn, the rest of the npm eco system would not be affected, so you're not really guaranteeing anything

No, it IS guaranteeing something. If people are NOT using yarn then they don't care about the problem.

> people using yarn can still use their own yarn.lock to achieve the same effect

Only if the dependencies for deepstream work when they generate their own lock file. Otherwise, no, you are wrong.

> you add more more thing that has to be maintained, are you prepared to maintain the lock file each time a bug fix for any of these dependencies have been released (which the non yarn users would get)?

I won't even comment on this.

**Comment by ronag** [comment]
This is more of a question of whether we want to be able to guarantee deterministic dependencies or don't think it's worth the "hassle".

**Comment by ronag** [comment]
@yasserf: This is relevant for the server as well.

**Comment by yasserf** [comment]
Using package-lock.json now 👍
