### ISSUE TITLE
Infinite loop when deleting record in same listen pattern

### ISSUE THREAD

**Issue by rsdrsd** [deepstreamIO/deepstream.io-client-js#322]
When I have the following code running in a single node.js backend client:
```
var ds = deepstreamClient('domain.app:80' ).login({username: 'provider', password: 'password'});
ds.record.listen('/chat/.*', (match, isSubscribed, response) => {
    var [_, userName] = match.match(/\/chat\/([0-9a-zA-Z]+)/);

    if (isSubscribed) {
        console.log('Add user', userName);
        response.accept();
    } else {
        console.log('Remove user', userName);
        ds.record.getRecord(`/chat/${userName}`).delete();
    }
});
```
It gets in some kind of infinite loop. It seems logical, because with:

    ds.record.getRecord(`/chat/${userName}`).delete();

it subscribes to the pattern again before it deleted the record. But when I look at the following example from the docs:
```
// Client B
client.record.listen('settings/.*', (match, isSubscribed, response) => {
  console.log(match) // 'settings/security'
  if (isSubscribed) {
    if (/* if you want to provide */) {
      response.accept()
      // star publishing to this record via `client.record.getRecord(match).set(/* data */)`
    } else {
      response.reject() // let deepstream ask another provider
    }
  } else {
    // stop publishing data
    client.record.getRecord(match).discard()
  }
})
```
almost the same happens, so I am wondering if this example is ok.

**Comment by yasserf** [comment]
You are right, this example needs some love.

> client.record.getRecord(match).discard()

is actually invalid, its a noop operation. But it should not get into an infinite loop! Can you test against 2.1.3?

**Comment by yasserf** [comment]
Subscribing to a record in the a provider is just not supported anymore (since 3.1) due to insane side effects
