### ISSUE TITLE
has provider doesn't always trigger

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io-client-js#325]

**Comment by seamusv** [comment]
Using the JS v2.2.1 SDK.  The callback for `client.record.has` contains an `err` parameter so assumed that it would be set if the user did not have access to the record.  Instead, the callback is not fired and the global error handler is executed with an `UNSOLICITED_MESSAGE`.

**Comment by AlexBHarley** [comment]
#384
