### ISSUE TITLE
'undefined' is not a valid property name on record

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#331]
Minor bug

**Comment by yasserf** [comment]
Associated stack trace perhaps? =D

**Comment by ronag** [comment]
@yasserf: Even better. A line of code!

https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/src/record/json-path.js#L144

**Comment by yasserf** [comment]
Can’t replicate anymore 😅
