### ISSUE TITLE
record.set not callbacked when data has not changed

### ISSUE THREAD

**Issue by escwald** [deepstreamIO/deepstream.io-client-js#335]
**Issue**
The callback added to record.set will only be called back if the client considers the data to be new.

**Reasoning**
As we see it, the user of the API wants to set X and then do something when record has value X. If this results in data not being changed due to old value already being X should not matter, since this is an optimisation.

**Comment by escwald** [comment]
I will add a pull-request with a fix for this as well.

**Comment by escwald** [comment]
I have now added a pull request #336 for the fix
I have also added a pull request [23](https://github.com/deepstreamIO/deepstream.io-client-specs/pull/23) in deepstream.io-client-specs to test this

**Comment by escwald** [comment]
@yasserf Do you think this is reasonable to fix? I have added a PR for a suggestion to fix it plus a spec test for it.

**Comment by escwald** [comment]
Added a new PR #339 that uses setImmediate instead of synchronous callback.

**Comment by bastilimbach** [comment]
@escwald Great work 👍 I debugged my code for the last 3 hours to find out that the callback doesn't get called if the data is the same. Looking forward to this fix in #339!

**Comment by yasserf** [comment]
This has been merged. Many thanks for raising and the PR!
