### ISSUE TITLE
Listener reconnect bug

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#337]
Consider the following scenario:

- Server is down
- Client starts listening (queues LISTEN)
- ACK timeout
- Server is up
- Client connects
- Client sends queued LISTEN message
- but it's already timed out???

I don't think the client should queue LISTEN until AFTER the server is connected. 

The behavior of reconnecting after having connected once is different from when the client has never been connected.

**Comment by yasserf** [comment]
This shouldn't happen with 2.1.2 since we don't register ack timeouts unless the connection is open, and clear them down once it closes.

**Comment by yasserf** [comment]
We now ignore all acks that occur while the connection is down:
```
AckTimeoutRegistry.prototype.add = function (timeout) {
  const timeoutDuration = timeout.timeout || this._options.subscriptionTimeout

  if (this._client.getConnectionState() !== C.CONNECTION_STATE.OPEN || timeoutDuration < 1) {
    return -1
  }
```

So this should no longer be an issue.
