### ISSUE TITLE
Global variable leak

### ISSUE THREAD

**Issue by drinchev** [deepstreamIO/deepstream.io-client-js#344]
Hey guys!

Thank you for the awesome product.

I just wanted to let you know that I found a global variable leak in one line of `single-notifier.js`.

https://github.com/deepstreamIO/deepstream.io-client-js/blob/9f30ce4f610a4ee44cb4c0f9b944c250346cf251/src/utils/single-notifier.js#L90

```        
	for( i=0; i < entries.length; i++ ) {
//           ^ missing `let i=0;`
		entry = entries[ i ];
		this._ackTimeoutRegistry.remove({
			ackId: entry.ackId
		});
		entry.callback( error, data );
	}
```

Is this intentional?

**Comment by WolframHempel** [comment]
Oh dear, thanks for raising - yeah, that should be within the scope

**Comment by yasserf** [comment]
Fixed (this motivated us to use eslint/babel in this release)

Thanks!
