### ISSUE TITLE
Use the same eslint config as the rest of deepstream

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io-client-js#345]

**Comment by ralphtheninja** [comment]
Have you thought about using `standard`? A lot of js projects use it already.

**Comment by yasserf** [comment]
Yeah, but they allow var which I'm trying to remove. We are pretty much identical except we have stricter rules -> we pass standard and then some I think

**Comment by ronag** [comment]
You don't pass standard since you don't have space between function names and parentheses.

**Comment by yasserf** [comment]
=(

**Comment by yasserf** [comment]
Other than the selection of linting tools ( easier for us to use a specific one everyone ), are you okay with the open PR? 

https://github.com/deepstreamIO/deepstream.io-client-js/pulls

It included babel but only for changing const/let to var and allows arrow functions, didn't change anything else yet.

Been thinking about how much time it would take to build a new js client with lessons learnt and it is doesn't make much sense. We are going to have an 'unofficial' nodeJS version that works directly on our C++ sdk so we can consume all of the same tests.

**Comment by yasserf** [comment]
Done!
