### ISSUE TITLE
delete on a list not triggered on all clients

### ISSUE THREAD

**Issue by BezMaster** [deepstreamIO/deepstream.io-client-js#356]
I have a probleme with the delete event available in the list object. All my client's list are ready and subscribing this delete event but only one of us received it.
Below you can find my implementation

```
            this.myList.on( 'ready', this.onStackReady);
            this.myList.on( 'entry-added', this.onMessageAdded);
            this.myList.on( 'entry-removed', this.onMessageRemoved);
            this.myList.on( 'delete', this.onStackDelete);
            this.myList.on( 'discard', this.onStackDiscard);
            this.myList.on( 'error', this.onStackError);
```

Is it normal ?

**Comment by yasserf** [comment]
Nope, bug open on server ->

https://github.com/deepstreamIO/deepstream.io/issues/533

This may be fixed on master, need to check!

**Comment by yasserf** [comment]
This should be fixed in latest release of deepstream.io 2.2.0
