### ISSUE TITLE
v2.1.3 dist no longer compiled for non-es6?

### ISSUE THREAD

**Issue by petemill** [deepstreamIO/deepstream.io-client-js#363]
v2.1.2 worked fine in non-es6 browsers (like PhantomJS) whereas v2.1.3 does not (complains about the existance of `const`).  Perhaps the pre-publish build did not fire for v2.1.3? Or does this no longer support non es6 browsers?

Thanks

**Comment by yasserf** [comment]
@petemill thanks for raising!

We definitely still support older browsers. Question is, are you bundling the client into your own bundle or including the `deepstream.js` or `deepstream.min.js` file?

**Comment by sergej-kurakin** [comment]
Having same issue... used "deepstream.io-client-js": "^2.1.1" in package.json and now builds are broken.

**Comment by yasserf** [comment]
are you running with node 0.12?

**Comment by sergej-kurakin** [comment]
Node version: v6.10.0, karma tests gets broken.

`SyntaxError: Unexpected token 'const'`

Downgraded to `2.1.1` - issue gone.

**Comment by yasserf** [comment]
Just release 2.1.4, it should resolve the issue. Would you mind checking?

**Comment by yasserf** [comment]
Hey, so release 2.1.4 should fix this issue.

I'm sorry for any problems this caused, and we have safeguards in check to ensure this does not happen again going forward.

**Comment by petemill** [comment]
FYI I was using normal `require('deepstream.io-client-js')` in a webpack app, and test under PhantomJS any user with similar configuration would most likely be doing straight require instead of `require('deepstream.io-client-js/dist/deepstream.min.js')` since locking the path dependency makes it harder to maintain if package developers move files around.

**Comment by yasserf** [comment]
Yup, the problem that we had is if we point towards dist (browserified) nodeJS support would suffer and if we pointed toward src it wasn't backwards compatible. It's just a setup I haven't seen as often and hence wasn't caught by any automated tests.

Thank you for raising it! And please let me know if the solution worked for you
