### ISSUE TITLE
ERROR: RPC already registered

### ISSUE THREAD

**Issue by hydrarulz** [deepstreamIO/deepstream.io-client-js#367]
I'm using version `deepstream.io-client-js@2.1.4`

And from time to time I get this kind of errors.

```
Error: RPC getBlock already registered
    at RpcHandler.provide (/root/blockchain-processor/node_modules/deepstream.io-client-js/dist/lib/rpc/rpc-handler.js:57:11)
    at DeepStream.provide (/root/blockchain-processor/lib/providers/DeepStream.js:76:21)
```
I expect not to get this error because I should be able to register multiple RPC providers to the same deepstream server `deepstream.io@2.1.6`

Deepstream server code
``` javascript
var Deepstream = require('deepstream.io');

var server = new Deepstream({
        rpcAckTimeout: 10 * 3600 * 1000,
        rpcTimeout: 10 * 3600 * 1000,
});

server.on('started', function() {
        console.log('started');
})

server.start();
```

**Comment by yasserf** [comment]
Problem is in client code. Login currently calls on every reconnect which maybe recreating your application. Putting a guard in place to ensure initialization occurs only once might help!

**Comment by hydrarulz** [comment]
Thanks, that seemed to be the issue
