### ISSUE TITLE
Transaction Hook

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#377]
We are using deepstream with mobx. One problem we've encountered is that we need to wrap all updates originating from a deepstream record tick into a mobx transaction for performance reasons. So we've basically ended up with the following hack:

```js
const orgHandleMessages = ds._connection._handleMessages
ds._connection._handleMessages = (...x) => mobx.transaction(() => orgHandleMessages(...x))
```

Anyone got ideas how to make a cleaner solution?

**Comment by yasserf** [comment]
Closing due to lack of response =(
