### ISSUE TITLE
Persistent record-store on client

### ISSUE THREAD

**Issue by andrewkvavlewhite** [deepstreamIO/deepstream.io-client-js#379]
Is there a way to subscribe to record changes without having the record sent to the client upon subscription? I'm using this for a react-native app that will be persisting record data. I'm trying to make it so when the app terminates and reopens all the required record data doesn't get resent over the wire when the client resubscribes, only the records that are outdated.

**Comment by yasserf** [comment]
Yes! This is super outdated obviously but for those reading this in 2019 onwards we now store the actual data locally on the client, which means when you subscribe on a reconnect you only request the head and only if the version is different we request the data itself!
