### ISSUE TITLE
MULTIPLE_SUBSCRIPTIONS if calling getRecord or subscribe when client is disconnected

### ISSUE THREAD

**Issue by oldlam** [deepstreamIO/deepstream.io-client-js#389]
as title says, to re-produce:
when the client is disconnected, call **getRecord** or **record.subscribe**,
and then once the connection resumed, the server would show logs with **MULTIPLE_SUBSCRIPTIONS | repeat supscription to ...**

I'd like to know whether it's a bug in the client or it's not supposed to call them when connection lost?
thanks!

**Comment by yasserf** [comment]
This was a bug in the client where it probably sent more than one subscribe to the server. This has been fixed in V4 by instead of queuing messages as strings we only create the messages once the subscription is back, makes each message unique.
