### ISSUE TITLE
Unable to set nodeSocketOptions in TypeScript

### ISSUE THREAD

**Issue by villeraikko** [deepstreamIO/deepstream.io-client-js#394]
I'm using nodeSocketOptions to pass certificate paths to the websocket connection. Everything seems to work when using plain NodeJS, but TypeScript compiler gives me this error:

`Object literal may only specify known properties, and 'nodeSocketOptions' does not exist in type 'Options'.`

It seems that nodeSocketOptions is not included in Options interface in client.d.ts.

**Comment by yasserf** [comment]
Closing as we can't actually tell what the nodeSocketOptions are since it depends on the websocket library your using to make a connection.
