### ISSUE TITLE
VERSION_EXISTS

### ISSUE THREAD

**Issue by Chinafreak** [deepstreamIO/deepstream.io-client-js#397]
Hello,

what kind of "warning" is this which I'm getting from server?

VERSION_EXISTS | 9f4c6397-8af0-40a7-af42-f1dd42d0048d tried to update record ch/gameLeft/9f4c6397-8af0-40a7-af42-f1dd42d0048d to version 2 but it already was 0

I'm getting this error at this code from server:

`
client.record.getRecord("ch/gameLeft/"+data.secretCode).subscribe((d)=>{ ... })
`
Callback is not called from subscribe but it should be!

this is the code which I sent from client to server:
`
client.record.getRecord("ch/gameLeft/"+data.secretCode).set({cancelled: true, code: data.secretCode, gameIndex: gameIndex, game: gameCode});
`

I'm using deepstream client 2.2.1 and deepstream server 2.4.0 (both node.js) for server and deepstream.io.client-js 2.2.1 for client.

**Comment by yasserf** [comment]
if you get a version exists it means the server hasn't recieved the messages in order and can't save it to the database

sorry for late reply too!

**Comment by Chinafreak** [comment]
No worries. I fixed it already. Sometimes I'm getting this error but that's rather my fault. Thank you anywayw! :D

**Comment by Chinafreak** [comment]
@rknash18 sorry I can't remember anymore. It was 2 years ago... 😰
