### ISSUE TITLE
Are you deprecating the callback on record.set?

### ISSUE THREAD

**Issue by jpbecotte** [deepstreamIO/deepstream.io-client-js#398]
In your new doc (https://deepstreamhub.com/docs/client-js/datasync-record/#set), we see that there's no argument for a callback for the `set` method. Was that intentional? If yes, you should write a deprecation notice because that change is not backward compatible. Thank you!

**Comment by AlexBHarley** [comment]
@jpbecotte good catch. We have no plans to deprecate write acknowledgements, looks like it might have got lost moving our docs over. We'll get it up soon.

**Comment by tzapu** [comment]
this seems to be still missing
