### ISSUE TITLE
Is this expected behaviour?

### ISSUE THREAD

**Issue by mattkirwan** [deepstreamIO/deepstream.io-client-js#404]
Hopefully someone can clarify what/why I'm seeing this.

There is a short video accompanying this so it can be easily seen.

In essence though from my limited understanding I should be seeing the length of the list array increasing in `node-client` everytime I add a unique record into `adjust.js`

`node-client`

```
#!/usr/bin/node
const deepstream = require('deepstream.io-client-js');

let client = deepstream('-')

client.login();

let list = client.record.getList('test/list');

list.subscribe((entries) => {
    console.log(`List changed. ${entries.length} entries.`);
});
```

`adjust.js`

```
#!/usr/bin/node

const deepstream = require('deepstream.io-client-js');
const client = deepstream('-');

client.login();

let recordName = `test/${client.getUid()}`;
let record = client.record.getRecord(recordName);

record.set({some:'data'});

record.whenReady(() => {
    let list = client.record.getList(`test/list`);
    list.whenReady(() => {
        list.addEntry(recordName);
    });

    list.on('entry-added', () => {
        console.log(`Added: ${recordName}`);
    });
});
```

This is using DeepstreamHub app.

As you can see from the video: https://www.youtube.com/watch?v=RgGyTwpvAS8
the `list.subscribe` doesn't always pick up the added list entry.

I've got to be misunderstanding a basic concept here. Any help is appreciated.

**Comment by jdmnd** [comment]
Hi @mattkirwan 
Thanks for letting us know. This isn't expected behaviour at all. We are currently experiencing some issues with cache timeouts in deepstreamHub. As you're seeing in the video, records are being successfully written to the database, but sometimes the updates are not being broadcast. 
We'll get this fixed as soon as possible, and I'll keep you posted.

John

**Comment by jdmnd** [comment]
The issue has been resolved on our end. Let us know if you have any other issues. 
John

**Comment by mattkirwan** [comment]
Perfect 👌 Thank you for your quick response.
