### ISSUE TITLE
When remote update fails, local copy of record is still updated

### ISSUE THREAD

**Issue by dannywieser** [deepstreamIO/deepstream.io-client-js#440]
See attached test case.

Scenario is:
* permissions are setup to disallow write/delete on a record (in my test case those permissions are completely disabled, in the real-world scenario the write/delete is based on a role in the application)
* client without permissions attempts to call .set on a record that they do not have permissions to set
* the update fails, a MESSAGE_DENIED error is broadcast
* HOWEVER, listeners for the updated record are still fired, and the value returned for .get on the record is the new value that actually has not been changed.  The local client now has a record that is no longer in sync with the remote record!

In Record.prototype.set, this code:

```
  this._sendUpdate(path, data, config);
  this._applyChange(newValue);
```

Will send the update over the socket and then locally apply the change with no error-checking on success of updating the remote state.  Based on this code, it would appear that this type of issue could happen with other errors outside the permission use-case, since the local update does no error handling for issues with the remote update.

[deepstream_test.html.zip](https://github.com/deepstreamIO/deepstream.io-client-js/files/1502512/deepstream_test.html.zip)

**Comment by yasserf** [comment]
Hey, thanks for raising! We are aware of this issue and should have it fixed in v4. Denying permissions is actually meant to be a way to stop the server from accepting Invalid data more than the client, for example a denied event would still emit locally (as if it was offline). What we will do is essentially make message denied do a merge conflict on the client and then notify listeners that it’s data has been reverted. Would that work for you?

**Comment by dannywieser** [comment]
Thanks for the reply.  Your proposed solution does sound like it should work, although I think it's critical that the merge conflict be identified so the client can provide some feedback as to why the data has changed.  I will being testing with the v4 beta.

I would advocate for an option to have .set() be handled as an atomic transaction. For real-time multi-user applications, it is often important that the state of the client not change until it's actually been remotely synced.

An simple use case would be an application that provides an online class with multiple attendees and each attendee has the ability to raise their hand via the application.  When an attendee presses the button to raise their hand, there is little value in having the application know locally that their hand is raised prior to it being remotely synced. In fact, if the attendee sees their hand raised in the application prior to a remote sync it may be very misleading that this state is visible to other users and that they can expect some type of response.  A scenario like this really requires confirmation of the remote change and/or notice of an error before the local client is updated.

Going back to your current v4 solution, imagine that the local client data indicates my hand is raised, but then sometime later a merge conflict is triggered and data is reverted.  As I noted above, this scenario requires some type of specific reason code to be provided so the user can be informed "something went wrong and your hand wasn't actually raised", etc.

**Comment by yasserf** [comment]
While I understand your point, this defeats the main concept of how records work, which is never caring if the state is synced (reduces branches massively).

If you want to ensure that the server is sync'd you could either do it via a
```
setWithAck(..,. () => {
  // your local variable here that is not on the record
})
```
or you could do it the old fashioned way of making an RPC which the backend then used to update a record, giving your logic a centralised place.

**Comment by dannywieser** [comment]
Thanks for the feedback, I came to the same conclusion about using the callback mechanism as the trigger to set the local record.  Looking through the V4 code, I see that there is an offlineDirty flag being set, and as I mention in my last comment I think that type of flag on a local record will be very useful.

I'll close this issue, I believe I have all the detail I need - thanks.
