### ISSUE TITLE
set triggerNow to false does not work if I subscribe the record directly

### ISSUE THREAD

**Issue by hdtp** [deepstreamIO/deepstream.io-client-js#445]
Hi,
I am using deepstream.io-client-js 2.3.0.
I found that if I do `client.record.getRecord(recordName).subscribe(callback , false)`
the callback is still triggered immediately.
But if I do `client.record.getRecord(recordName).whenReady(rec => { rec.subscribe(callback , false) })`, it works as expected, the callback is not triggered.

**Comment by yasserf** [comment]
Hey @hdtp

Thats because the data initially isn't loaded, and hence as soon as it is returned from the server it is triggered. I would recommend always using whenReady if possible. In v4 its as simple as

```
record = client.record.getRecord(name)
await whenReady()
record.subscribe(callback)
```

meaning you don't need to worry about callback nesting.

**Comment by hdtp** [comment]
Well noted. Thanks!

**Comment by yasserf** [comment]
Happy that made sense, closing then!
