### ISSUE TITLE
Anonymous record does not emit event ready upon calling setName

### ISSUE THREAD

**Issue by jshrt** [deepstreamIO/deepstream.io-client-js#447]
Using the following script:

```
const deepstream = require('deepstream.io-client-js')

const { expect } = require('chai')
const { spy } = require('sinon')

const serveraddress = '172.17.0.1:6020'

const client = deepstream(serveraddress)

client
  .login({})
  .then(() => {
    const onReadySpy = spy()

    const anonyRecord = client.record.getAnonymousRecord()

    anonyRecord.on('ready', onReadySpy)

    anonyRecord.setName('cars/bmw')

    setTimeout(() => {
      anonyRecord.setName('cars/ford')
    }, 1000)

    setTimeout(() => {
      let exceptionCaught = false
      try {
        expect(onReadySpy.callCount).to.equal(2)
      } catch (e) {
        exceptionCaught = true
      } finally {
        console.log('Assertion', exceptionCaught ? 'failed' : 'succeeded')        
        process.exit(exceptionCaught)
      }
    }, 6 * 1000)
  })
  .catch(err => {
    console.log('Error logging in:', err)
  })
```

I was not able to trigger the anonymous record's `ready` event upon calling setName, where per this script, it should be called twice.

---
_You can find the script in:https://github.com/deepstreamIO/test-scripts/commit/6f44667cb6ebe0053ff6f82e35e34c1ebbfb54bd_

**Comment by yasserf** [comment]
Nice catch (not sure if we want it to tbh, but its worth an issue!)

**Comment by jshrt** [comment]
The documentation of the previous versions talks about it, is this going to be deprecated?

**Comment by yasserf** [comment]
If the previous version supports it then no. Makes sense to have it, its just a bit tricky since whenReady can be emitted more than once (which records can't).

**Comment by yasserf** [comment]
Not sure if we want this still tbh. If your using an anonymous record you probably just want to depend on the subscribe callback or have an entirely different event to indicate it can be called more than once  (since it then shouldn't be a promise). Closing as I doubt anyone uses it this extensively and would be confusing to get the API right
