### ISSUE TITLE
Client just hangs with no error or warning when server address is faulty

### ISSUE THREAD

**Issue by jshrt** [deepstreamIO/deepstream.io-client-js#451]
Using the following script: (_which tries to connect to a deepstream server with faulty address_)
```
const deepstream = require('deepstream.io-client-js')
const client = deepstream('10.11.0.1:6020')
client.on('error', console.log)
client.login({}).then(() => {
    console.log('logged')
}).catch(err => {
    console.log('error')
})
```

Nothing happens, where as the client should probably warn or throw an error

**Comment by yasserf** [comment]
Nice catch, this is a regression from v3

**Comment by jaime-ez** [comment]
This seems to be a websocket library problem (both node and browser), the connection will fail when you pass an invalid domain or IP, but hang when passing a correct domain with wrong port, or any ip address (without response) from port, for example:

google.com -> fails
google.com:6020 -> hangs

64.233.186.139 -> fails (64.233.186.139 is a google ip)
64.233.186.139:6020 -> hangs

157.254.130.212 -> hangs (157.254.130.212 is random generated ip)
157.254.130.212:6020 -> hangs

Here's a fiddle to test in browser: http://jsfiddle.net/nzm1oLdk/

**Comment by yasserf** [comment]
Awesome, yeah I seen that in other protocols as well, ssh for example just hangs when I try to access a machine and the port is closed (not sure if related)

So two ways to think about this:

1) the logic is faulty generally so we close 
2) we close connection with a timeout and go into an error state if we don’t get a response from deepstream in time

Eitherways the ping timeout should kick in so you would be told theirs an error, just much further into the future

Thoughts?

**Comment by jaime-ez** [comment]
I'll go for option 1. The timeout kicks in after 2 minutes.
