### ISSUE TITLE
UnableToResolveError: Unable to resolve module `url`

### ISSUE THREAD

**Issue by chinmaygit** [deepstreamIO/deepstream.io-client-js#452]
Bundling `index.js`  [development, non-minified]  99.8% (884/885), failed.
error: bundling failed: UnableToResolveError: Unable to resolve module `url` from `/node_modules/deepstream.io-client-js/dist/lib/utils/utils.js`: Module does not exist in the module map.

**Comment by yasserf** [comment]
Fixed in 4.0, not sure why that happened in 3 though since we had a few webpack issues. Sorry for long response rate =(
