### ISSUE TITLE
Ability to see what channels the client are subscribed to

### ISSUE THREAD

**Issue by whitelizard** [deepstreamIO/deepstream.io-client-js#453]
I would very much like to be able to read out what channels the client already are subscribed to, like so:

`client.event.emitter.eventNames()`

I understand it is not an option to tag the emitter as public instead of private, instead there is needed some other public method on the client EventHandler for this feature (that basically just returns `emitter.eventNames()`).

**Comment by whitelizard** [comment]
Any chance for this small change to be made soon? :)

**Comment by yasserf** [comment]
Sorry for delay on this =(. If your still interested I can put this into V3, let me know

**Comment by whitelizard** [comment]
It would probably still be an interesting feature, yes

**Comment by yasserf** [comment]
Are you still actively using V3? As if not happy to add into V4 rather double the work but hard to tell since I was away for a bit when these issues were posted 😅🙈

**Comment by whitelizard** [comment]
We are using v3 right now

**Comment by yasserf** [comment]
```
ds.event.subscribe('hello', () => {})
ds.event.subscribe('goodbye', () => {})
console.log(ds.event.eventNames())

ds.record.getRecord('bonjour')
ds.record.getRecord('what')
console.log(ds.record.recordNames())

ds.rpc.provide('rpc', () => {})
ds.rpc.provide('rpc2', () => {})
console.log(ds.rpc.providerNames())

/**
 * [ 'hello', 'goodbye' ]
 * [ 'bonjour', 'what' ]
 * [ 'rpc', 'rpc2' ]
 */
```

Added in 2.3.1 👍  let me know how it goes

**Comment by yasserf** [comment]
Also added in V4 😁
