### ISSUE TITLE
`presence.subscribe(callback)` event not fired

### ISSUE THREAD

**Issue by teckays** [deepstreamIO/deepstream.io-client-js#457]
**Deepstream version**: `deepstreamio/deepstream.io:v4.0.0-rc.2-alpine`
**NodeJS SDK version**: `deepstream.io-client-js@4.0.0-beta.1`
**NodeJS version**: `v8.7.0`
**OS**: `macOS High Sierra`

Running the following script:
```
const { deepstream } = require('deepstream.io-client-js')
const client = deepstream('ws://localhost:6020/deepstream')

client.on('error', (error, event, topic) => {
  console.log('error, event, topic: ', error, event, topic)
})
client.on('connectionStateChanged', state => {
  console.log('state: ', state);
})

const clientUid = client.getUid()
client.login({ identity: 'teckays', clientUid, password: 'asd' }, (success, data) => {
  if (!success) throw new Error('Client Service login failed!')
  console.log('Client service logged in')

  client.presence.subscribe((username, online) => {
    console.log('username, online: ', username, online)
  })
  
  client.presence.getAll(usernames => {
    console.log("Online: ", usernames)
  })
})
```
outputs the following result:
```
state:  AWAITING_CONNECTION
state:  CHALLENGING
parseResults:  [ { topic: 2, action: 3, isAck: false, isError: false } ]
state:  AWAITING_AUTHENTICATION
state:  AUTHENTICATING
parseResults:  [ { topic: 3, action: 2, isAck: false, isError: false } ]
state:  OPEN
Client service logged in
parseResults:  [ { topic: 7, action: 11, isAck: true, isError: false } ]
parseResults:  [ { topic: 7, action: 2, names: [], isAck: false, isError: false } ]
Online:  null
```
**NOTE**: `parseResults` comes from here: [console.log('parseResults: ', parseResults)](https://github.com/deepstreamIO/deepstream.io-client-js/blob/f0983cf77db1b25ef8f6528d93c537e193e6810f/dist/src/connection/socket-factory.js#L12)

As you can see, the event doesn't reach the `presence.subscribe()` callback. I could track it up until [here](https://github.com/deepstreamIO/deepstream.io-client-js/blob/f0983cf77db1b25ef8f6528d93c537e193e6810f/dist/src/connection/socket-factory.js#L19) where the message is received in the `socketFactory.onmessage()` method which then gets parsed and sent to `socketFactory. onparsedmessage()` method which is empty.
```
socket.onparsedmessage = () => { };
```
I am not 100% sure I completely understand how this works but I couldn't trace any messages leading back to either:
- `this.subscriptionEmitter.on(user, callback);`
- `this.globalSubscriptionEmitter.on(ONLY_EVENT, userOrCallback);`
listeners.

Hope this helps!

**Comment by teckays** [comment]
After this comment on slack by @yasserf 

> You got to login with a username
> That's what is used for presence

I've tried with the following code:
`subscribe.js`
```
client.on('connectionStateChanged', state => {
  console.log('state: ', state);
})

const clientUid = client.getUid()
client.login({ username: 'BE', clientUid, password: 'password' }, (success, data) => {
  if (!success) throw new Error('Client Service login failed!')
  client.presence.subscribe((username, online) => {
    console.log('Is online?', username, online)
  })
  
  client.presence.getAll(usernames => {
    console.log("All:  ", usernames)
  })
})
```
output:
```
state:  AWAITING_CONNECTION
state:  CHALLENGING
state:  AWAITING_AUTHENTICATION
state:  AUTHENTICATING
state:  OPEN
All:   null
```

`login.js`
```
client.on('connectionStateChanged', state => {
  console.log('state: ', state);
})

const clientUid = client.getUid()
client.login({ username: 'teckays', clientUid, password: 'asd' }, (success, data) => {
  if (!success) throw new Error('Client Service login failed!')
  console.log('data: ', data)
})
```
output:
```
state:  AWAITING_CONNECTION
state:  CHALLENGING
state:  AWAITING_AUTHENTICATION
state:  AUTHENTICATING
state:  OPEN
data:  { id: 'e1531689-f703-4f3c-9ce1-5fef88c46f52',
  username: 'teckays',
  clientUid: 'jclzju9f-1wq7tlaqvgf' }
```
again, I've tried both: `client.presence.subscribe((username, online) => {})` and `client.presence.subscribe('teckays', online => {})` same result, the callback is not being called.

**Comment by teckays** [comment]
**UPDATE**
After debugging the `PresenceHandler.handle(message)` I've noticed that the only 2 messages are being passed to this function:
```
{ topic: 7, action: 11, isAck: true, isError: false }
{ topic: 7, action: 2, names: [], isAck: false, isError: false } // QUERY_ALL_RESPONSE
```
in the case of `subscribe(cb)` the `this.globalSubscriptionEmitter.emit()` is fired when `message.action` is either `PRESENCE_ACTIONS.PRESENCE_JOIN_ALL` or `PRESENCE_ACTIONS.PRESENCE_LEAVE_ALL` which using the code:
```
client.on('error', (error, event, topic) => {
  console.log('error, event, topic: ', error, event, topic)
})
client.on('connectionStateChanged', state => {
  console.log('state: ', state);
})

const clientUid = client.getUid()
client.login({ username: 'SERVICE', password: 'password' }, (success, data) => {
  if (!success) throw new Error('Client Service login failed!')
  
  client.presence.subscribe((username, online) => {
    console.log('Is online?', username, online)
  })
  client.presence.getAll(usernames => {
    console.log("All:  ", usernames)
  })
})
```
doesn't seem to fire the `PRESENCE_ACTIONS.PRESENCE_JOIN_ALL` event action.

**Comment by samuk159** [comment]
Same problem here. client.presence.getAll() always returns an empty array.

**Comment by crapthings** [comment]
await client.presence.getAll() works

**Comment by yasserf** [comment]
Yeah I been using these and it all seems fine, also the tests all pass correctly. Closing for now but please reopen if you run into issue again

**Comment by kyeno** [comment]
I have just ran into this issue myself. Using custom authentication HTTP plugin, but still sending "username" as login parameter. presence.getAll() returns null and empty array, presence subscribes do not work at all.

**Comment by yasserf** [comment]
Using the custom authentication requires you to return the user id on the post callback.

```
How you construct the service behind the url endpoint is up to you and your application stack, but it should return the relevant http response code and either a username string, or a JSON:

{
    "id":"chris",
    "clientData": {},
    "serverData": {}
}
```

https://deepstream.io/tutorials/core/auth/http-webhook/
