### ISSUE TITLE
Subscribe can trigger "now", even when triggerNow argument is falsy

### ISSUE THREAD

**Issue by escwald** [deepstreamIO/deepstream.io-client-js#464]
Subscribe does not wait until record is ready when triggerNow is false. This can create a scenario where a subscription is set up to not trigger now, but then triggers right away anyway, probably due to that the record becomes "ready" after the subscription is added to the eventEmitter.

Here is how the code looks in 2.3.0, in record.subscribe
```
if (args.triggerNow) {
  this.whenReady(() => {
    this._eventEmitter.on(args.path, args.callback)
    args.callback(this.get(args.path))
  })
} else {
  this._eventEmitter.on(args.path, args.callback)
}
```

If I rewrite the code like this (which I also think looks cleaner), then it works for me
```
this.whenReady(() => {
  this._eventEmitter.on(args.path, args.callback)
  if (args.triggerNow) args.callback(this.get(args.path))
})
```

The same issue seems to still exist on master, in subscribe() of record-core.ts
```
if (args.triggerNow) {
  this.whenReady(null, () => {
    this.emitter.on(args.path || '', args.callback)
    args.callback(this.get(args.path))
  })
} else {
  this.emitter.on(args.path || '', args.callback)
}
```

So it looks like you could rewrite it to this
```
this.whenReady(null, () => {
  this.emitter.on(args.path || '', args.callback)

  if (args.triggerNow) {
    args.callback(this.get(args.path))
  }
})
```
(this has not been tested by me, because we still use 2.3.0 in our project)

**Comment by yasserf** [comment]
Hey, this logic was actually contained for backwards compatibility in master. We could remove it.. but I'm not sure how badly it would effect other users. Any suggestions would be awesome!

**Comment by yasserf** [comment]
This is a really good point, if we do decide to break it now is the time. Just not sure what side effects their might be. Will flag to look at before V4 gets out of RC

**Comment by yasserf** [comment]
Okay I’m going to put this logic in as whenReady fires now when offline as well as it fallbacks to local storage. Never understood why it fired immediately when not ready tbh, initialising with an empty object is just a waste of cpu cycles
