### ISSUE TITLE
RecordStatic doesn't expose 'setData' method in TypeScript definitions file.

### ISSUE THREAD

**Issue by viridia** [deepstreamIO/deepstream.io-client-js#465]
If I cast 'client.record' to 'any', setData() works fine. It's just the type definition that is missing.

This is in version 2.3.0.

**Comment by yasserf** [comment]
Thanks for raising. You can update the typings for 2.3 in the master branch and raise a PR if you like!

**Comment by yasserf** [comment]
FYI V4 is written using typescript so declaration files are auto generated 👍 

The APIs is almost fully backwards compatible (no longer as much chaining) with some tiny changes so we won't be backporting to V3
