### ISSUE TITLE
Deepstream restored entries and records out of the blue

### ISSUE THREAD

**Issue by Serfenia** [deepstreamIO/deepstream.io-client-js#467]
Hi There,

I'm using deepstream in combination with redis. I have three clients:
- A web app, subscribing on and off from three deepstream lists. Only adds/remove an entry from one list (the app is 'owner' of the list)
- A docker service running a Node.js app, modifying two lists and it's records.
- A second docker service running a Node.js app, modifying the records of one of the lists of the first docker service, and also subscribing to the list that is owned by the web app.

Friday night all our records and entries cleared up nicely, have all three lists in an empty state with all records deleted. Saturday night however (25 hours later), two lists restored their data in full, with all records, out of the blue. The state restored itself with the latest state of entries and records it had before entries got removed/records got deleted.

At that point of time, there was nothing going on in our system, nor was any user logged in in our web app. Is there any explanation how this could've happened? Has anyone experienced this before? Am I doing something completely wrong?

Merge strategies are: 
- Web App: Remote wins
- First docker service: Local wins
- Second docker service: Local wins

FYI Our web app and services are running on an Ubuntu 16 server, and deepstream/redis are running on separate Ubuntu server.

**Comment by Serfenia** [comment]
FYI: Apparently our web-app had the 'local wins' merge strategy, and today when our web-app re-connected, all records and entries that were added were removed again.

But how can a merge strategy cause something like this. There is very little documentation about how stuff is handled over multiple clients internally

**Comment by Raven5650** [comment]
any news on this?

**Comment by Serfenia** [comment]
@Raven5650 I've actually stopped using Deepstream because of it's surprising behaviour when there are multiple clients reading the same records and lists. It's a disaster at the moment.

**Comment by yasserf** [comment]
hey there, sorry about the abysmal response time.

I'm not actually sure why that happened, my only guess is local wins overwrote any remove version with your local state which is empty. Local wins is therefore something you would only expect to set if you actually modified the client while offline using the `record.setMergeStrategy(local)` as opposed to a blanket cover.

For future reference we have done a large redesign in V4 to better control state transitions and log any weird errors.

Sorry again for not getting back to you on this earlier, would have loved the extra input. If you decide to give V4 another shot I'm currently fully focused on this project and working directly with some users to ensure its up to their standards, with almost all improvements going straight back into core.

**Comment by yasserf** [comment]
For now theres this if anyone passes this issue:

https://deepstreamhub.com/tutorials/guides/handling-data-conflicts/
