### ISSUE TITLE
Error Parsing Messages in MessageParser.parse

### ISSUE THREAD

**Issue by roark** [deepstreamIO/deepstream.io-client-js#469]
Hi Deepstream team,

I'm attempting to try out Deepstream, along with your Node.js libs and am running into an issue. Several seconds after calling `client.login()` my Node.js app crashes with the following error:

```
deepstream.io-client-js/dist/lib/message/message-parser.js:37
  var rawMessages = message.split(C.MESSAGE_SEPERATOR);
                            ^
TypeError: message.split is not a function
```

When I dove a bit deeper, it appears that the `message` argument passed to `MessageParser.parse` is a:
` <Buffer 82 01 00 00 00 00 00 00>` rather than an expected `<String>`

This seems possibly related to: https://github.com/deepstreamIO/deepstream.io/issues/509 & https://github.com/deepstreamIO/deepstream.io/issues/538

However, I'm experiencing these issues within the `deepstream.io-client-js` npm package, and not from the deepstream server itself. 

I'm currently using `deepstream.io-client-js 2.3.0`, `Deepstream 4.0.0-rc.4` and `Node 8.2.1` (also tried 6.3.1).

Possibly I'm configuring something wrong, as I am completely new to these libraries. But it appears to be a bug as it shows itself immediately upon following the quick start tutorial.

Let me know if there is any more info I can provide. Or if it may be a mis-configuration then maybe point me in the right direction. Many thanks!

**Comment by roark** [comment]
It appears this is an issue with `Deepstream 4.0.0-rc.x` as I downgraded to `Deepstream 3.1.1` and everything began to work as expected.

As an fyi, `4.0.0-rc.4` is currently the version offered through Homebrew and therefore likely the starting place for most new users.

**Comment by ravindranrahul** [comment]
Meanwhile, if anyone needs help downgrading to 3.1.1 as  temporary solution here is how 

* `brew cask uninstall deepstream`
* `brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/c74d22db2654cf11966f3d2b4cce170d393f9196/Casks/deepstream.rb`

**Comment by yasserf** [comment]
Current version now seems to be 3.1.5

Thanks for raising!
