### ISSUE TITLE
Deepstream v4 - Faulty transition

### ISSUE THREAD

**Issue by CatEars** [deepstreamIO/deepstream.io-client-js#473]
Hi, while investigating records not resubscribing we found the fault to be a record that reached a failed transition. We suspect that the record was trying to load before the first connection to the server was made, therefore causing the offline mode to kick in and put the version of the record at 1, while it was 0 on the server. I am not sure if the version of the record is the problem, but that means it reaches [this](https://github.com/deepstreamIO/deepstream.io-client-js/blob/v4/src/record/record-core.ts#L625) branch of `handleHeadResponse()` in `RecordCore`, suggesting that the record was deleted and recreated remotely (which was not the case). I'll list the states the record traversed in its state-machine, but we will not look further into it.

Transitions inside state machine:

| # | this.oldState   | transitionName      |
|---|-----------------|---------------------|
| 0 | INITIAL         | OFFLINE_LOAD        |
| 1 | LOADING_OFFLINE | OFFLINE_LOADED      |
| 2 | READY           | OFFLINE_RESUBSCRIBE |
| 3 | RESUBSCRIBING   | OFFLINE_RESUBSCRIBE |

On transition `#3` it fails because it resubscribes while already resubscribing.

**Comment by yasserf** [comment]
Fixed in rc.25
