### ISSUE TITLE
Recovering from suspend / hibernate

### ISSUE THREAD

**Issue by viridia** [deepstreamIO/deepstream.io-client-js#475]
One of the most frequent errors I see in our frontend logs is "heartbeat not received in the last 60000 milliseconds". I believe this may be caused when a user walks away from their screen for more than a few minutes and their computer goes to sleep, which causes the machine to go offline. When it comes back online, deepstream notices that it hasn't gotten any heartbeats in a while and signals an error.

There's a browser event which can be used to inform the app when the offline / online status changes. I'm wondering if it would make sense to have a deepstream API method which I can call when this happens.

Alternatively, if someone has a better idea for handling these kinds of cases, I'd be interested to hear it.

**Comment by yasserf** [comment]
This has been added in V4 with a `pause` and `async resume` callback that stops the connection from trying to constantly be alive!
