### ISSUE TITLE
state RECONNECTING is not retrying connection on startup (v 4.0.0-rc.30)

### ISSUE THREAD

**Issue by KrishnaPG** [deepstreamIO/deepstream.io-client-js#495]
#### Problem
Client is not establishing connection to the server, when the clients starts **before** the server.

Consider the below simple scenario:

    1. Server not started
    2. Client (infinite retry attempts allowed) started
    3. Client goes into RECONNECTING state
    4. Client blurts out error (shown below)
    5. Then nothing happens. No state changes, no retry attempts, nothing
    6. Start the server. 
    7. No difference on the client side. Nothing happens

Error:
````
{"target":{"_events":{},"_eventsCount":4,"readyState":3,"protived":false,"_closeFrameSent":false,"_closeMessage":"","_closceiver":null,"_sender":null,"_socket":null,"_bufferedAmount":":0,"url":"ws://127.0.0.1:6020/deepstream","_req":null},"type":"errsage":"connect ECONNREFUSED 127.0.0.1:6020","error":{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6020}}
````
Now, upon inspecting the code, the culprit is: https://github.com/deepstreamIO/deepstream.io-client-js/blob/afbf7c05414d6fab2a3d9e1557523d695d18ed49/src/connection/connection.ts#L63 

That initialization with `-1` is blocking the `tryReconnect()` attempts (refer below code): https://github.com/deepstreamIO/deepstream.io-client-js/blob/afbf7c05414d6fab2a3d9e1557523d695d18ed49/src/connection/connection.ts#L478 

#### Fix

Initializing the `reconnectTimeout` with null, as below, makes the `tryReconnect` work as expected (and client successfully connects to the server whenever server is available)
````
this.reconnectTimeout = null
````

**Comment by yasserf** [comment]
Thank you for raising! I’ll aim to get a fix out ASAP.

**Comment by yasserf** [comment]
Fix should be in rc.35 (getting quite high in ex numbers haha, but I’m not in a rush to get V4 out and still adding breaking changes every now and then so...) 😅

**Comment by KrishnaPG** [comment]
Checked it - the fix is working. Thank you.
