### ISSUE TITLE
record change event triggered for all paths (even though only one path changed) v4.0.0-rc.35

### ISSUE THREAD

**Issue by KrishnaPG** [deepstreamIO/deepstream.io-client-js#496]
Client version: 4.0.0-rc.35

`Record.set()` for one path is triggering the change event for all subscribers (for other paths also). For example, 
````
record.set('userDrawnItems', { x: 10, y: 10 })
````
triggering event for path: "settings" also. Looks like the equality checking  for objects is not working properly: https://github.com/deepstreamIO/deepstream.io-client-js/blob/ca1537127c22dfad4c9aa8e6b1a2fda6e2884458/src/record/record-core.ts#L745 

In this case 
````
newValue = { theme: "dark" }
oldValue = { theme: "dark" }
````
and the above condition `newValue !== oldValue`  is evaluating to `true` incorrectly (instead of `false`, since that particular value did not change).

![image](https://user-images.githubusercontent.com/4610831/60493132-e53f4800-9cc9-11e9-854e-390611a84f02.png)

**Comment by yasserf** [comment]
Good point, not sure how to fix this without adding serialisation since
object references change on update events. Will need to think about it.
Thanks for raising!

**Comment by yasserf** [comment]
Was this issue not in V3 btw?

**Comment by daviderenger** [comment]
We added a deep compare, it's definitely fast enough an fixes this!

https://github.com/briteback/deepstream.io-client-js/blob/master/src/record/record-core.ts

**Comment by yasserf** [comment]
Awesome, will add that then. Thanks! 😁

**Comment by KrishnaPG** [comment]
- For the point regarding V3, I do not remember seeing this then. After moving to 4 rc 35 started seeing this.
- Regarding the performance, one point I observed is, the `record.set()` calls `record.core.applyChange` in the code. While the `record.set` accepts a `path` (that tells which `key` in the JSON we are changing the record), it however does not pass that `path` to the `core.applyChange` method: https://github.com/deepstreamIO/deepstream.io-client-js/blob/ca1537127c22dfad4c9aa8e6b1a2fda6e2884458/src/record/record-core.ts#L219

Only the `newValue` is passed, which makes the `applyChange` method to probe the complete key-value space of the JSON record. IMO, passing the `path` as additional param to the `applyChange` method could reduce the search space by guiding / restricting the sub-sections of the `key`  - since only the sub-trees of the `path` node can change (if any). Currently, it looks like the whole record is being searched for changes:
https://github.com/deepstreamIO/deepstream.io-client-js/blob/ca1537127c22dfad4c9aa8e6b1a2fda6e2884458/src/record/record-core.ts#L740-L748

**Comment by KrishnaPG** [comment]
Or may be not, never mind. Looks like the code is going over the subscriber paths, not record paths.

**Comment by yasserf** [comment]
https://github.com/deepstreamIO/deepstream.io-client-js/issues/522
