### ISSUE TITLE
subscribing to a path of a record containing an object will invoke the callback every time the record is modified

### ISSUE THREAD

**Issue by hhanh00** [deepstreamIO/deepstream.io-client-js#499]
regardless of whether the actual value in the path has changed or not.

This is possibly by design though it is not what one may expect. It works if the path contains a primitive value. The root cause seems to be in the comparison between newValue and oldValue which uses !==. For objects, this will always return true. 

A shallow or deep compare seems to be preferable. As a work around, I subscribe to the object id and then retrieve the object in the callback.

**Comment by jaime-ez** [comment]
Hi, this seems to be fixed. I'm closing for now. Feel free the reopen if problem persists.
