### ISSUE TITLE
Auto-resubscribe webRTC after connection drop

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io-client-js#50]
Re-send subscriptions and listens for webRTC after a connection drop

**Comment by kimberleyhansen** [comment]
Bump

**Comment by yasserf** [comment]
After a few discussions regarding the complexity of reallife webRTC signaling and scenarios we have decided the core team won't be supporting any fixes/maintenance going forward and concentrate on all other core features.  Sorry for inconvenience!  =(

**Comment by ronag** [comment]
Sorry to hear...
