### ISSUE TITLE
Errors from custom merge strategy are ignored and record.set callback never fires

### ISSUE THREAD

**Issue by alanhoff** [deepstreamIO/deepstream.io-client-js#504]
Hello there,

I've found that if a custom merge strategy throws an error then the callback for `record.set` and `record.setWithAck` will never fire.

In the example below I would expect that `record.setWithAck` got called back with `new Error('No conflicts allowed')` so I could wait for the record to get updated then try again, like a transaction.

You can observe this behavior by running the following example simultaneously on two separated browser tabs, one of the tabs will stop logging `tx done` when a conflict is detected. 

```javascript
const deepstream = require('@deepstream/client');
const client = deepstream('ws://localhost:6020');

function CustomMergeStrategy(
  localValue,
  localVersion,
  remoteValue,
  remoteVersion,
  callback
) {
  callback(new Error('No conflicts allowed'));
}

client.login({}, async () => {
  const record = client.record.getRecord('hello-world');

  while (true) {
    await record.setWithAck({time: Date.now()});

    console.log('tx done');
  }
});
```

**Comment by alanhoff** [comment]
Yeah it looks like the error is indeed ignored:

https://github.com/deepstreamIO/deepstream.io-client-js/blob/6fd7463abed3d6fef68e5c2b19dc8a32e8cb99dd/src/record/record-handler.ts#L561

But I'm not sure why the callback is never called.

**Comment by yasserf** [comment]
Thank you for raising! Will look into it soon!

**Comment by yasserf** [comment]
Fixed! Sorry for the delay. This requires both a server and client update.
