### ISSUE TITLE
'List' ready event doesn't fire?

### ISSUE THREAD

**Issue by crapthings** [deepstreamIO/deepstream.io-client-js#506]
video

https://streamable.com/q5trm

bad one

```js
SubscribePeers = () => {
    this.peers = this.connection.record.getList('peers')


    this.peers.on('ready', () => {
      // this should fire once i think
      const peers = this.peers.getEntries()
      console.log('ready', peers)
    })

  }
```

good one

```js
SubscribePeers = async () => {
    this.peers = this.connection.record.getList('peers')

    await this.peers.whenReady()

    const peers = this.peers.getEntries()
      console.log('ready', peers)

  }
```

"@deepstream/client": "^4.0.4",
    "@deepstream/server": "^4.1.0",

**Comment by yasserf** [comment]
This will be resolved by removing the ready event entirely from V5, it’s
duplicated using the  whenReady callback.

**Comment by jaime-ez** [comment]
Hi, indeed it seems that the ready event is no longer triggered for records nor lists. I'll push the change to the documentation and close this issue for now. Feel free to reopen if problem persists.
