### ISSUE TITLE
close method leaks resources

### ISSUE THREAD

**Issue by alanhoff** [deepstreamIO/deepstream.io-client-js#509]
I'm using latest `@deepstream/client` and latest `node`, the following code can be used to reproduce the issue:

```javascript
const deeptream = require('@deepstream/client');

const client = deeptream('ws://localhost:6020');

client.on('connectionStateChanged', state => {
  if (state !== 'CLOSED') return;

  console.log('Closed, Node.js should exit');

  setTimeout(() => {
    console.log('Node.js failed to exit');
  }, 1000).unref();
});

client.login({}, () => {
  console.log('Logged in');
  client.close();
});
```

Node should properly exit after `client.close()` gets called, but instead `Node.js failed to exit` is printed and the process keeps running until we kill it. This indicates that there's a I/O operation still going on or a timer wasn't properly canceled.

You should check if the WebSocket connection is being properly closed.

**Comment by yasserf** [comment]
Thanks for raising

It’s probably a timer like you mentioned, will get a fix out in V5

**Comment by yasserf** [comment]
Just tested this locally and it works as expected

```bash
client $ ts-node test.ts 

Logged in
Closed, Node.js should exit

client$ 
```

**Comment by alanhoff** [comment]
Ah, it looks this behavior can only be observed when using node.js v8, if using `>=v10` it works as expected. I'm closing this issue for now since it looks like it isn't related to deepstream itself.
