### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by Sopamo** [deepstreamIO/deepstream.io-client-js#513]
Thanks for providing such a great library.

We recently upgraded to Deepstream 4, but just now realized that v4 doesn't seem to support IE11. I've got the example code here in a jsfiddle: https://jsfiddle.net/uzqye0x3/

I already did some tinkering and it seems like IE11 support should be possible with just a bit of tweaking. I'm not 100% sure though.

I'd love to get some feedback if dropping IE11 support was a concious decision and/or if supporting it is planned in the future.

**Comment by yasserf** [comment]
hey! sorry for the late reply. There should be no reason it doesn't work in IE11 since it just uses WebSockets. If your still using this please let me know what the error is, thanks!

**Comment by Sopamo** [comment]
I tried it again with the latest version (5.0.6) and the error is still present. I think the issue comes from @deepstream/protobuf, as this is the error message I see in IE11:
![image](https://user-images.githubusercontent.com/1202596/75147527-d0527180-56fd-11ea-87eb-da02bf8b14da.png)
Which is this part of my app.js:
![image](https://user-images.githubusercontent.com/1202596/75147552-dcd6ca00-56fd-11ea-92c8-e1ce52c7210f.png)
That code comes from @deepstream/protobuf. 

Deepstream version 2.3.4 works fine in IE11.

**Comment by yasserf** [comment]
Interesting! Do you know if IE11 supports let/const?

**Comment by Sopamo** [comment]
Partly, see caniuse for [let](https://caniuse.com/#search=let) and [const](https://caniuse.com/#search=const)

**Comment by Sopamo** [comment]
@yasserf Is IE11 support something you are going to work on? If not - would you be open to pull requests for IE11 support?

**Comment by yasserf** [comment]
hey! Sorry I didn't have time to look into this, but yeah, 100% open for all PRs that don't reduce code quality!

**Comment by jaime-ez** [comment]
I'm going to close this untill the PR arrives...
