### ISSUE TITLE
Promises and callbacks hang forever on conflict

### ISSUE THREAD

**Issue by alanhoff** [deepstreamIO/deepstream.io-client-js#519]
Whenever a client needs to run a merge strategy, any callback or promise related to the merged record will hang forever. This code can be used to replicate the problem, one just need to open two tabs running the same code and will notice that one of the tabs will simply stop logging `tx done` after a few seconds.

```javascript
const {DeepstreamClient} = require('@deepstream/client');
const client = new DeepstreamClient('ws://localhost:6020');

client.login({}, async () => {
  const record = client.record.getRecord('hello-world');

  while (true) {
    await record.setWithAck({time: Date.now()});

    console.log('tx done');
  }
});
``` 

This is also related to #504

**Comment by yasserf** [comment]
Fixed! Woo.

**Comment by yasserf** [comment]
This is now commited and is just pending change logs and a few more other small fixes to round up this release.

Thanks again for raising and apologies for the delay!
