### ISSUE TITLE
Error using 5.0.6 in the browser

### ISSUE THREAD

**Issue by valentinvichnal** [deepstreamIO/deepstream.io-client-js#520]
```
Uncaught Error: Cannot find module 'url'
```

**Comment by valentinvichnal** [comment]
Maybe revert https://github.com/deepstreamIO/deepstream.io-client-js/commit/9ed575bbf87a8b4d36924db57bfeded12803fdba ?

**Comment by yasserf** [comment]
Yeah, seems like it was a fail merge. Do you want to do this?

**Comment by yasserf** [comment]
Reverted and released 5.0.7
