### ISSUE TITLE
dist directory/.js-file for browser is missing

### ISSUE THREAD

**Issue by davidbehler** [deepstreamIO/deepstream.io-client-js#528]
I'm trying to upgrade from deepstream 2.4 to 5.x and can't find the appropriate client .js file to include. For 2.x the releases included a dist directory with the compiled .js files that could be used in the browser, but for the 5.x releases this folder and the compiled .js files are missing.

Is there a reason for this? If so, what's the best way for me to get the client .js I need?

**Comment by davidbehler** [comment]
I found this URL in on of your [tutorials](https://deepstream.io/tutorials/getting-started/javascript/): https://cdn.deepstream.io/js/client/latest/ds.min.js

Is that the right way to go?

**Comment by jaime-ez** [comment]
You can install from npm with `npm install @deepstream/client`, or clone the repo and execute `npm install && npm run tsc` and the dist folder will be compiled

**Comment by davidbehler** [comment]
I did that, but neither deepstream.js nor deepstream-client.js expose a DeepstreamClient constructor when including via script-tag into my website.

They both look significantly different than the file on the cdn and I think I'm missing a processing step or something.

**Comment by jaime-ez** [comment]
I ran this index.html file: 
```
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="https://cdn.deepstream.io/js/client/latest/ds.min.js" charset="utf-8">
    </script>
  </head>
  <body>
    <p>HI</p>
    <script type="text/javascript">
      var client = new window.DeepstreamClient('localhost:6020')
      client.login({}, function(success) {
        console.log('success', success)
      })
    </script>
  </body>
</html>
```

While runngin an open deepstream server in port 6020 and had no issues, the client connected succesfully.

**Comment by davidbehler** [comment]
Yes, the file from CDN works fine. But no where is it explicitly stated that the file from CDN should be used. 

Previous (pre 5.x) releases included a ready-to-use .js file and that's what I was looking for, since we are upgrading to 5.x.

This issue can be closed as far as I'm concerned.

**Comment by slachtar** [comment]
I think, in the README file, there should be an explicit link to the client browser version.
https://cdn.deepstream.io/js/client/latest/ds.min.js
I'm migrating from 2.x to 5.x and the doc links to dist/... which doesn't exist.

**Comment by slachtar** [comment]
Sorry @jaime-ez to bother you,
but this code doesn't work, same result when pointing to ds.min.js under client\dist\bundle from a fresh nodejs client installation.

```
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="https://cdn.deepstream.io/js/client/latest/ds.min.js" charset="utf-8">
    </script>
  </head>
  <body>
    <p>HI</p>
    <script type="text/javascript">
      var client = new window.DeepstreamClient('localhost:6020')
      client.login({}, function(success) {
        console.log('success', success)
      })
    </script>
  </body>
</html>
```

**Comment by jaime-ez** [comment]
Hi, take a look at the docs: https://deepstream.io/tutorials/getting-started/javascript/#getting-the-client
The client should be retrieved like this:
```
const { DeepstreamClient } = window.DeepstreamClient
const client = new DeepstreamClient('localhost:6020')
client.login()
```

Let me know if there is a problem

**Comment by slachtar** [comment]
Thank you, your code works:

`<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdn.deepstream.io/js/client/latest/ds.min.js"></script>
  </head>
  <body>
    <input type="text" />
    <script type="text/javascript">
      window.onload = function () {
        //js goes here
		const { DeepstreamClient } = window.DeepstreamClient;
		const client = new DeepstreamClient('localhost:6020');
		client.login();
      }
    </script>
  </body>
</html>`

**Comment by jaime-ez** [comment]
Pull requests are welcome!

**Comment by slachtar** [comment]
I've submitted a pull request.
I've another question if you don't mind, is it possible to use deepstream client with old syntax, I mean `var dsclient = deepstream('localhost:6020');`
and avoid the ES6 syntax, because I've a constraint in my javascript framework compiler which didn't understand ES6 syntax.

**Comment by slachtar** [comment]
I don't know if it's a hack or not, but I managed to fix the problem by using ES6 in the app index.html which is not seen by compiler, there I attached deepstream to window like this:
```
<script type="text/javascript">
      window.onload = function () {
        //js goes here
	const { DeepstreamClient } = window.DeepstreamClient;
	window.deepstream = DeepstreamClient;
      }
  </script>
```
Then inside my other js files which are being compiled to one single .js, I refer to window.deepstream like this:
```
var dsclient = new window.deepstream('localhost:6020');
client.login({"username": "myuser", "password": "mypass", "role": "user"}, function(success, data){
	console.log("success", success);
});
```
