### ISSUE TITLE
Deepstream-client have not worked in ReactNative 

### ISSUE THREAD

**Issue by codecrack3** [deepstreamIO/deepstream.io-client-js#529]
When I tried to connect to Deepstream and log in I get an error message. 
Does the current library does not support React Native?. Anybody can help me?, I hope to see a reply soon. Thanks

![image](https://user-images.githubusercontent.com/9525576/83345726-b6e64480-a340-11ea-82ab-dd32517fcbb0.png)

Note: I use the latest version Deepstream client and ReactNative

**Comment by jaime-ez** [comment]
Hi this sould be fixed in the next release. In the meantime you can download from the latest tag [v5.1.1](https://github.com/deepstreamIO/deepstream.io-client-js/tree/v5.1.1), build the client and try it out.

**Comment by jaime-ez** [comment]
Hi, this is solved and published on the latest client release v5.1.2.

Please feel free to reopen the issue if you still have problems.

**Comment by yasserf** [comment]
Thanks @jaime-ez!
