### ISSUE TITLE
C and Options are not exported from dist/bundle/ds.min.js

### ISSUE THREAD

**Issue by timarandras** [deepstreamIO/deepstream.io-client-js#533]
This works with `@deepstream/client@5.1.1`:

```javascript
const { DeepstreamClient,C } = require('@deepstream/client');
```
Both `DeepstreamClient` and `C` are destructured properly.

But with `@deepstream/client@5.1.2`, due to `package.json:main` (reasonably) changed to point to `dist/bundle/ds.min.js`, it seems to fail to export `C` and `Options` despite the export is there in `deepstream-client.d.ts`:

```javascript
export { DeepstreamClient, C, Options };
```
When trying to import/require `@deepstream/client@5.1.2`:

```javascript
const { DeepstreamClient,C, Options } = require('@deepstream/client');
```
`C` and `Options` are undefined. Only the first export (`DeepstreamClient`) is exported.

It seems webpack/terser somehow gets rid of those exports.

I had to work around this using an additional import/require from directly the constants.
```javascript
const C = require('@deepstream/client/dist/src/constants');
```

**Comment by yasserf** [comment]
@jaime-ez any idea how we can get this to work? (Or if we just mention its a breaking change)
