### ISSUE TITLE
ACCEPT_TIMEOUT weired behavior

### ISSUE THREAD

**Issue by slachtar** [deepstreamIO/deepstream.io-client-js#551]
I'm working on a slow server (sandbox for tests) and set the following values on server config
```rpc:
  # Timeout for client RPC acknowledgement
  ackTimeout: 180000
  # Timeout for actual RPC provider response
  responseTimeout: 180000
```

I do use default acceptTimout on client side (which is 6000 I think).
When I make an rpc call twice for the same function, the second call raises an ACCEPT_TIMEOUT error and the rpc callback is called which is fine for me.

The problem is that after some time (few seconds), the rpc callback is called again but now with result returned from backend.
Is this the expected behavior?

When this happens, I can continue making other rpc calls, but cannot subscribe to records anymore!

**Comment by jaime-ez** [comment]
Hi, I was just testing a similar problem and came to see if it had been raised before! I'm seeing the behaviour with `rpcResponseTimeout`:

If I declare on the client options a value for rpcResponseTimeout that is less than the server default or declared, I get a RESPONSE_TIMEOUT error, and then the response from the server. This should not happen in my opinion becasue it leads to bugs: you handle the error but then the success response is called anyway.

I think the solution is to add a isComplete flag on rpc.ts file, I'll make a pull with the proposed changes

**Comment by slachtar** [comment]
Yes, that was exactly the behavior with the accept timeout too. After that
error, the deepstream client stops working properly.

It will be great if you could fix it.

Thank you,

**Comment by jaime-ez** [comment]
Well, the problem has been eliminated on version 5.2.0 (to be released). The client no longer controls rpc timeouts. I'll update the website soon

**Comment by slachtar** [comment]
Thank you, nice work.
