### ISSUE TITLE
In chrome, new DeepstreamClient, then the XmlHttpRequest won't work.

### ISSUE THREAD

**Issue by wildfire810** [deepstreamIO/deepstream.io-client-js#576]
**Describe the bug**
In chrome, new DeepstreamClient, then the XmlHttpRequest won't work.

**To Reproduce**
1. import { DeepstreamClient } from "@deepstream/client";
2. new DeepstreamClient('localhost:6020');
3. XmlHttpRequest will always timeout.

**Server version**
6.2.0

**Protocol (binary or text)**
websocket binary

**Websocket server (node-http or uws)**
node-http

**Server OS**
win10

**Node version**
18.0.0

**Server config**
default

**Client (Js, Java, other) and client version**
chrome 102.0.5005.63

**Client config**
default. connect to localhost

**Comment by jaime-ez** [comment]
Hi, I don't know how you're calling the deepstream client on your html. Take a lok here on how to do it:
https://deepstreamio.github.io/docs/tutorials/getting-started/javascript
Let me know how it goes
