### ISSUE TITLE
DeepstreamClient - RPC ResponseTimeout

### ISSUE THREAD

**Issue by mmartinsdev** [deepstreamIO/deepstream.io-client-js#579]
Hi,

I upgrade my application from Deepstream 4.X to Depstream 6.X. .Previously, the constructor take rpcResponseTimeout properties. After the migration, I can't find this properties. 

I have already defined this option in the server configuration YAML
`rpc:
  ackTimeout: 1000
  responseTimeout: 300000
`

That's enough in 6.X version?

Thank-you

**Comment by jaime-ez** [comment]
Hi, yes, in previous versions the rpc timeouts where duplicated between server and client, and not syncronized, so the client might have called a timeout and not the server or viceversa.

Starting client v5.2.0 it is handled server side only as described in the [changelog](https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/CHANGELOG.md#520---20201229).
Therefore the values you set on your server configuration are the only valid ones.

Cheers
