### ISSUE TITLE
connection proxy

### ISSUE THREAD

**Issue by davidmoshal** [deepstreamIO/deepstream.io-client-js#63]
Hi, just wondering if it's possible to piggyback Deepstream Client connections over the same port as the server,  as is done with socket.io and engine.io.

i.e: instead of:
` deepstream_client('localhost:6021')`

I'd like to just use this on the client:
`deepstream_client()`

and have server-side middleware register on a known (configurable) path, e.g: /deepstream/, with the port being taken from the current url.

i.e: http communication with DS would piggy-back on the same port.

That way I can be sure that corporate customers can just use one port to connect to the backend?

Dave

**Comment by WolframHempel** [comment]
Hi @davidmoshal ,

thanks for raising this. You're making a very good point (in fact a related issue has come up before). For the next release of deepstream.io I'd propose adding support for the following two [server options](http://deepstream.io/docs/deepstream.html)

```javascript
/**
* An instance of a Node HTTP server object. Allows to use
* deepstream from within Node HTTP server implementations, 
* e.g. ExpressJS
*
* @type http.Server
* @default null
*/
server.set( 'httpServer', myHttpServer );

/**
* A subpath for browser clients to connect to. Corresponds
* to the client's path option
*
* @type String
* @default '/engine.io'
*/
server.set( 'urlPath', '/ds-connections' );
```

Please let me know if that would satisfy your requirements.

**Comment by davidmoshal** [comment]
I'm fine with any config option, as long as I can piggyback one port.    
Given that you are using `engine.io` this should be trivial to implement, no?

https://github.com/socketio/engine.io

**Comment by inxilpro** [comment]
See https://github.com/deepstreamIO/deepstream.io/pull/92

**Comment by yasserf** [comment]
We should test this and see if it just works out of the box now that  deepstreamIO/deepstream.io#92 is implemented

**Comment by yasserf** [comment]
Connection defaults to /engine.io path on same host and port as current url
