### ISSUE TITLE
Automatically call discard() when all subscriptions are unsubscribed.

### ISSUE THREAD

**Issue by petemill** [deepstreamIO/deepstream.io-client-js#69]
Whenever `record.unsubscribe()` is called, could the client detect if it has any more subscriptions remaining after that one, and if not, inform the server it is no longer interested in the record anymore (i.e. what `record.discard()` does?

It seems like this should be a transparent occurance, for performance and for preventing users having to re-invent the same logic all the time. Would a client every want the server to still notify record changes for a record it has 0 subscriptions to?

**Comment by petemill** [comment]
Actually, I'm guessing this isn't appropriate because that means the client would not be notified of changes to records it has gotten, and it does not know if some code will attempt to perform a `get()` on that record, so it needs to keep the data up to date, right?

**Comment by yasserf** [comment]
Yep.

Another reason would also be for versioning and merges. You want to be on the latest version before updating it to ensure you don't have any unforeseen merge issues.

If a client does not need the record anymore they could discard it and then retrieve it again when required. Is this the 'same logic' you mentioned in the description?

It's an interesting suggestion, curious to hear other opinions.
