### ISSUE TITLE
Record listens should return the amount of subscribers interested in the record

### ISSUE THREAD

**Issue by Lalem001** [deepstreamIO/deepstream.io-client-js#74]
Given the [ds-demo-provider](https://github.com/deepstreamIO/ds-demo-provider), generator will never stop generating after first subscription.

Stepping through the logic:

- Server and provider are started
- Client connects and subscribes to `FX/*` record
- [onSubscription](https://github.com/deepstreamIO/ds-demo-provider/blob/master/backend/fx-data-provider.js#L19) is called
  - `isSubscribed` is true
  - `fx-data-provider` **subscribes** to `FX/*` record
  - **There are now two subscribers!**
- Client disconnects.
- One subscriber (fx-data-provider) remains, onSubscription is not called.

I was hoping to have on-demand providers in my current project.
Any suggestions on how to resolve this issue?

**Comment by yasserf** [comment]
The ds-demo dependencies are out of date. Will look at it in the next hour and keep you updated.

**Comment by yasserf** [comment]
Hey! Right so you were totally correct. This is actually a design issue I'll discuss with the rest of the core team tomorrow.

We might need to have a different kind of record which is a *silent* requester so that is doesn't let deepstream it has the the record. I think that would probably be quite a bit of work tho so will sleep over a solution.

This works great for events so far since they are stateless, but I can see this happening often with records.

Thanks for raising!

**Comment by yasserf** [comment]
So we have decided on the following as an API change

record.listen( '/bob/', function( recordName, numberOfSubscribers ) {
} );

This way if numberOfSubscribers === 1 and your already providing it you would know to stop.
This is also the least invasive in terms of APIs.

Thoughts?

**Comment by Lalem001** [comment]
That is a reasonable solution.

Will the function be called per subscription? What happens when transitioning from 1 to 2 subscribers? 1 to 0?

**Comment by yasserf** [comment]
Should be called everytime a match occur. Will try implementing today and let you know!

**Comment by Lalem001** [comment]
Any updates on this issue?

**Comment by yasserf** [comment]
Not yet, it will be in our next release but we are currently focusing on getting a couple more tutorials out on how to use deepstream with different front-end libraries.

**Comment by Lalem001** [comment]
Not to derail the original topic, but I am very interested to see these tutorials. Have any links?

**Comment by yasserf** [comment]
They are still a work in progress. Currently polymer elements and a react mixin. Should be issues on website repo you can follow!

**Comment by yasserf** [comment]
We need to think of a better way to indicate if a record is subscribed to or not than providing numbers.
