### ISSUE TITLE
Reduce the dependencies within the client bundle

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io-client-js#75]
Webpack provides a sleeker version of browserify. It's recommended by react and the JavaScript world seems to be moving towards it.  It might help us reduce the size of the client files be bundling less unneeded dependencies.

http://webpack.github.io/

**Comment by yasserf** [comment]
Webpack adds the same amount of dependencies, so changes the title for us to find a more generic approach
