### ISSUE TITLE
set isDestroyed = true and isReady flag before delete event

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io-client-js#77]
At the point in time the record emits a `delete` event, the isReady flag should already be set to false.

The isDestroyed flag is a bit trickier - currently it is used by the record internally to check if it still needs to be destroyed - we might need to introduce an additional internal flag for that so that

delete message received:
- isDestroyed: true
- isReady: false

**Comment by ronag** [comment]
Not sure, but this might tie into #209
