### ISSUE TITLE
Travis build seems to only run a small number of tests

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io-client-js#80]
The command it runs is correct, but it looks like it only runs about 20 tests (judging by the green dots) as opposed to the ~500 it should run.

![image](https://cloud.githubusercontent.com/assets/1503717/13546791/e8ffeaea-e2b8-11e5-9922-de74a3a40602.png)

**Comment by yasserf** [comment]
We can add a reporter to make results look shiny
