### ISSUE TITLE
Not working with webpack

### ISSUE THREAD

**Issue by alexanderchr** [deepstreamIO/deepstream.io-client-js#81]
I'm trying to use this client with webpack, but failing because of `require('net')` in TcpConnection. This happens because webpack tries to resolve all requires statically as opposed to browserify which does it lazily. 

I can see two ways to solve this:

1) Provide separate entry points for browser- and node environments
2) Use require.ensure to require engine.io/net. This is a better solution, but would make some of the constructors asynchronous and break the api.

Thoughts? With webpack quickly becoming the standard bundler I don't think this is something that can be ignored.

**Comment by jbilcke** [comment]
Hi, 

I had the same issue, I ended up doing solution 1:

```javascript
var path = require('path');
var webpack = require('webpack');

var node_modules = path.resolve(__dirname, 'node_modules');
var pathToDeepstream = path.resolve(node_modules, 'deepstream.io-client-js/dist/deepstream.min.js');

module.exports = {
  plugins: [
    new webpack.IgnorePlugin(new RegExp("^(net)$")),
  ],
  resolve: {
    alias: {
      'deepstream.io-client-js': pathToDeepstream
    }
  },
  ... rest of the config ..

}

**Comment by WolframHempel** [comment]
I completely agree and would love to add proper webpack support with the client library without users having to adjust their config. As webpack doesn't recoursively include webpack.config.js files from libraries, what would be the best approach to do this?

**Comment by WolframHempel** [comment]
Just released 0.4.3 that should work with WebPack...please re-open if the problem persists

**Comment by alexanderchr** [comment]
Thank you for the quick update. Works flawlessly, much better solution that what i had in mind.

Did you have any specific reason for excluding just `net` and not all of `TcpClient`? The less code in client builds the better.

**Comment by WolframHempel** [comment]
Very good point, we'll adjust it for the next release.
