### ISSUE TITLE
add advanced merge strategies

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io-client-js#82]
Add merge strategies that will be executed when the client encounters a version exists error. The following strategies will be supported

`C.MERGE_IF_NO_CONFLICT` (default) current and incoming version will be merged if neither a value nor a tree conflict exists.

`C.LOCAL_WINS` the clients current version will be used

`C.REMOTE_WINS` the incoming update will be used

`function(){}` - a custom function with the following signature
```javascript
function( localValue, remoteValue, recordName, recordVersion, callback ) {
    callback( error, mergedVersion );
}
```

merge strategies can be set in two places:
**global** as part of the client options
```javascript 
var ds = deepstream( 'localhost:6020', {
    /**
   * @ function mergeStrategy
   */
    mergeStrategy: C.REMOTE_WINS
});
```

**per record** on a per record basis
```javascript
var rec = ds.record.getRecord( 'some/record' );
rec.setMergeStrategy( function(){...});
```

**Comment by WolframHempel** [comment]
I'm really in two minds whether this should be done on the client or the server.

Benefits of merging on the client
Greater control, less load on the server, possibility for user interaction / user merging

Benefits of merging on the server
Clients in different languages don't all have to implement merging, centralized, both old and new data of the record are already present, quicker

Love to hear some thoughts...

**Comment by anilgulecha** [comment]
@WolframHempel for the sake of this issue can you comment on what was chosen, and point to docs if any?
