### ISSUE TITLE
Dump to local storage

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io-client-js#84]
In the event that a connection is unrecoverable, make the content of `Connection._queuedMessages` available to be saved locally until the connection comes back. Do this either by

a) providing a method to access the queued messages which can be used in conjunction with connection state change events

``` javascript
ds.on( 'connectionStateChanged', function( connectionState ) {
    if( connectionState === 'ERROR' ) {
        var queuedMessages = ds.getQueuedMessages();
       // do something with the queued messages, e.g.
      localStorage.setItem( 'backup' queuedMessages );
   }
});
```

this would require another hook to send an array of queued messages via the client, e.g. 

``` javascript
if( localStorage.queuedMessages ) {
    ds.sendMessages( queuedMessages );
}
```

which might be a bit confusing to users as `sendMessages` sounds like a central concept, yet is only used in rare recovery cases

b)  add a `backupToLocalStorage: true` option to the client (false by default) - which would be simpler, but can't be used in nodeJs - which could write it to a file...but that's where it gets complicated again

Thoughts?

**Comment by Svenskunganka** [comment]
Awesome idea Wolfram!

I lean towards the *b* option, as that would allow us to free up memory until the connection is regained (unless `ds.getQueuedMessages` already nukes the queue?). Although I still think we should make the hook overridable so a custom implementation can be added if required.

The Node.js part is a bit tricky indeed, but I think file storage is safe to go for. We could do some neat stream magic. What drawbacks do you see with file storage?

**Comment by WolframHempel** [comment]
The tricky bit with file storage is OS permissions. So far, deepstream doesn't need elevated permissions to run in production - which is a great position to be in. Introducing dumps to a file would be the only feature that now requires you to setup folder permissions etc for your deepstream project.

To be honest, I am leaning towards a - I appreciate it's a little less convenient, but there are numerous things you might want to do with your message dumps - in a large, distributed system you might for instance want to sent them to a log system or to a message queue to have them send by another client.

**Comment by n-scope** [comment]
I use deepstream with react-native. I would prefer a) as well, to be able to persist to AsyncStorage instead of local storage.
This feature would be a big help to implement offline-first mobile apps, if it's possible to re-submit saved messages after the application restarts

**Comment by yasserf** [comment]
This has been added in V4 (using a proper storage api). This also works for records though as events and RPCs shouldn't actually go through if the connection is down.
