### ISSUE TITLE
Subscription to changes in records not working properly

### ISSUE THREAD

**Issue by JBeCast** [deepstreamIO/deepstream.io-client-js#91]
The subscribers seem to get the updates only when I change a direct property on the record, but not when that property has a nested object as value (it doesn't work if it contains an array either).

First I thought it was related to utils.deepEquals, but the function seems to be working fine, so it looks like for some reason it's comparing two identical data structures whenever it gets called, even though I'm clearly changing the value of the record.

I had to override Record.prototype.set and Record.prototype._completeChange, removing every call to utils.deepEquals and now it's working the way it's supposed to work (or at least how I understood it should work according to deepstream.io's documentation).

**Comment by yasserf** [comment]
Can you let me know what version of deepstream.io-client-js your using? If I'm not mistaken there's a chance this might be related to #78

**Comment by JBeCast** [comment]
I happened to be using version 3.10, I've updated it to 4.3 and it seems to be working fine. It's really strange though, the first fix I tried was changing deepEquals so that it compared the 'stringified' version of both objects (exactly what you did) but it didn't seem to work.
Thanks for your quick answer! :)
