### ISSUE TITLE
on error event handler has weird arguments

### ISSUE THREAD

**Issue by timaschew** [deepstreamIO/deepstream.io-client-js#95]
If I subscribe to the error event via `ds.on('error', function(message, event, topic) {})`

I get this arguments on a permisson error:

```
["R", "MESSAGE_DENIED", "R"]
```

Seems that this line in the deepstream js client is calling these arguments https://github.com/deepstreamIO/deepstream.io-client-js/blob/7d29fab20c919e07d3baa7cc2cf9c85f65ab50a9/src/client.js#L175

But in this issue and in most lines of code the order is a different:
https://github.com/deepstreamIO/deepstream.io/issues/38#issuecomment-143563988

The incoming data from __ws.onmessage__ is `"4REMESSAGE_DENIEDRCRu/2"` <- cool formatting 😄 

and the creation of the array for the error handler happens here https://github.com/deepstreamIO/deepstream.io-client-js/blob/9f44da17fe08dd6616039e57d82177bf9d57674d/src/record/record-handler.js#L171

**Comment by WolframHempel** [comment]
Cheers,

that's a genuine problem - the order of arguments is different for some error callbacks. We'll need to fix that.

For this one, it's **R**ecord, MESSAGE_DENIED, **R**ead

**Comment by yasserf** [comment]
Fixed
