### ISSUE TITLE
Deepstream not updating object properties

### ISSUE THREAD

**Issue by drsirmrpresidentfathercharles** [deepstreamIO/deepstream.io-client-js#96]
Deepstream will not push an update to subscribers of a record if that record is an object which has a property that changes. Offending code:
    var myObject = {hello:1};
    ds.record.getRecord('myRecord').set('mySubrecord',myObject);
    //mySubrecord on this client returns {hello:1}, other clients {hello:1}
    myObject.hello = 2;
    //mySubrecord on this client returns {hello:1}, other clients {hello:1}
    ds.record.getRecord('myRecord').set('mySubrecord',myObject);
    //mySubrecord on this client returns {hello:2}, other clients {hello:1}
This is specifically happening using the node.js client at 0.5.0, node.js version 5.11.0, and node.js server at 0.9.0.

**Comment by drsirmrpresidentfathercharles** [comment]
Forgot to mention, if you change the last line to:
    ds.record.getRecord('myRecord').set('mySubrecord',Object.assign({},myObject))
It works flawlessly.

**Comment by WolframHempel** [comment]
Could I ask you to make sure you're using the latest version of the client library? This should have been fixed in release 0.4.2

**Comment by drsirmrpresidentfathercharles** [comment]
Running client 0.5.0.

**Comment by drsirmrpresidentfathercharles** [comment]
Found it. JSONPath sets its value at https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/src/record/json-path.js#L70. This set is by reference, so when an object property changes, the local copy of the record is updated, but connection.sendMessage is not called. Then, if you manually set the record, it shows as unmodified (https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/src/record/record.js#L102) so connection.sendMessage is still not called.

I don't know what the best solution is, but maybe a force update or copy on set would work.
